"use client";

import { useState } from "react";
import { 
  LikeIcon as LikeIconBase, 
  CommentIcon as CommentIconBase, 
  ShareIcon as ShareIconBase,
  AISparkleIcon 
} from "../icons";
import Icon from "../Icon";

// Helper to format counts (e.g., 2847 -> "2.8K")
const formatCount = (count) => {
  if (!count) return "0";
  if (count >= 1000000) return `${(count / 1000000).toFixed(1)}M`;
  if (count >= 1000) return `${(count / 1000).toFixed(1)}K`;
  return count.toString();
};

// Wrapper components with local CSS class overrides
const PublicIcon = () => <Icon name="globe-americas-filled" size={12} color="secondary" />;
const LikeIcon = () => <LikeIconBase size={20} className="mobile-post__ufi-icon" />;
const CommentIcon = () => <CommentIconBase size={20} className="mobile-post__ufi-icon" />;
const ShareIcon = () => <ShareIconBase size={20} className="mobile-post__ufi-icon" />;
const GenAiStarIcon = () => <AISparkleIcon size={12} color="currentColor" className="mobile-post__ai-icon" />;

const MobileGroupPost = ({
  group,
  post,
  onJoinGroup,
  onLike,
  onComment,
  onShare,
  hideAiBadge = false,
  hideSeeMore = false,
  noTruncateGroupName = false,
  maxLines = 3,
}) => {
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <article className="mobile-post">
      {/* Post Header - FDS Post Header component style */}
      <div className="mobile-post__post-header">
        <div 
          className={`mobile-post__post-header-left${noTruncateGroupName ? ' mobile-post__post-header-left--no-truncate' : ''}`}
          style={noTruncateGroupName ? { minWidth: 'auto', overflow: 'visible' } : undefined}
        >
          <div className="mobile-post__post-header-avatar-group">
            {/* Squircle - Group photo */}
            <div className="mobile-post__avatar-squircle">
              <img src={group.avatar} alt={group.name} />
            </div>
            {/* Circle overlay - Author photo */}
            <div className="mobile-post__avatar-circle">
              <img src={post.author.avatar} alt={post.author.name} />
            </div>
          </div>
          <div 
            className={`mobile-post__post-header-content${noTruncateGroupName ? ' mobile-post__post-header-content--no-truncate' : ''}`}
            style={noTruncateGroupName ? { minWidth: 'auto', overflow: 'visible' } : undefined}
          >
            <h2 
              className={`mobile-post__post-header-entity${noTruncateGroupName ? ' mobile-post__post-header-entity--no-truncate' : ''}`}
              style={noTruncateGroupName ? { whiteSpace: 'normal', overflow: 'visible', textOverflow: 'unset' } : undefined}
            >{group.name}</h2>
            <p className="mobile-post__post-header-meta">
              <span className="mobile-post__post-header-author">{post.author.name}</span>
              <span className="mobile-post__post-header-separator">·</span>
              <span>{post.author.date}</span>
              <span className="mobile-post__post-header-separator">·</span>
              <PublicIcon />
            </p>
          </div>
        </div>
      </div>

      {/* Post Title */}
      <div className="mobile-post__title">
        <h1>{post.title}</h1>
      </div>

      {/* AI Badge */}
      {post.aiGenerated && !hideAiBadge && (
        <div className="mobile-post__ai-badge">
          <GenAiStarIcon />
          <span>Title generated by AI from Meta</span>
        </div>
      )}

      {/* Post Body */}
      <div className="mobile-post__body">
        {hideSeeMore ? (
          <p>
            {post.body}
          </p>
        ) : isExpanded ? (
          post.body.split("\n\n").map((paragraph, idx) => (
            <p key={idx}>{paragraph}</p>
          ))
        ) : (
          <p>
            {post.body.substring(0, 205)}
            <span 
              className="mobile-post__see-more"
              onClick={() => setIsExpanded(true)}
            >
              ... See more
            </span>
          </p>
        )}
      </div>

      {/* UFI Buttons */}
      <div className="mobile-post__ufi">
        <div className="mobile-post__ufi-left">
          {/* Like */}
          <button className="mobile-post__ufi-action" onClick={onLike}>
            <LikeIcon />
            <span>{formatCount(post.reactions.total)}</span>
          </button>

          {/* Comments */}
          <button className="mobile-post__ufi-action" onClick={onComment}>
            <CommentIcon />
            <span>{formatCount(post.commentsCount)}</span>
          </button>

          {/* Share */}
          <button className="mobile-post__ufi-action" onClick={onShare}>
            <ShareIcon />
            <span>{formatCount(post.sharesCount)}</span>
          </button>
        </div>

        {/* Inline Reactions */}
        <div className="mobile-post__ufi-right">
          <div className="mobile-post__ufi-reactions">
            {post.reactions.like > 0 && (
              <img src="/images/reactions/like_default_40.png" alt="Like" />
            )}
            {post.reactions.love > 0 && (
              <img src="/images/reactions/love_default_40.png" alt="Love" />
            )}
          </div>
        </div>
      </div>
    </article>
  );
};

export default MobileGroupPost;

