// Marketplace search results - Stranger Things toys (Funko Pops and Legos)
export const marketplaceResults = [
  {
    id: "st-toy-1",
    type: "marketplace",
    title: "Stranger Things Funko Pop - Eleven with Eggos #421",
    groupName: "Facebook Marketplace",
    description: "Funko Pop Eleven holding Eggos waffles. Mint condition, never removed from box. A must-have for any collector!",
    price: "$25",
    originalPrice: null,
    location: "Seattle, WA",
    nearbyDistance: null,
    image: "/images/stranger-things-assets/images/marketplace/funko-pop.jpg",
    storeName: "Hawkins Pop Shop",
    storeIcon: "🎁",
    rating: 5.0,
    reviews: 89,
    href: "/m/marketplace/t1",
  },
  {
    id: "st-toy-2",
    type: "marketplace",
    title: "LEGO Stranger Things The Upside Down 75810 - Complete Set",
    groupName: "Facebook Marketplace",
    description: "Complete LEGO Stranger Things set featuring the Byers house in both dimensions. All pieces included, built once and displayed.",
    price: "$89",
    originalPrice: "$109",
    discount: "18% OFF",
    location: "Seattle, WA",
    nearbyDistance: "2 mi",
    image: "/images/stranger-things-assets/images/marketplace/lego.jpg",
    storeName: "Brick Builders Co",
    storeIcon: "🧱",
    rating: 4.9,
    reviews: 156,
    href: "/m/marketplace/t2",
  },
  {
    id: "st-toy-3",
    type: "marketplace",
    title: "Funko Pop Demogorgon Chase Edition #428 - RARE",
    groupName: "Facebook Marketplace",
    description: "Rare chase edition Demogorgon Funko Pop. Glow in the dark variant. Box in pristine condition. Serious collectors only!",
    price: "$85",
    originalPrice: "$45",
    discount: "RARE",
    location: "Seattle, WA",
    nearbyDistance: "5 mi",
    image: "/images/stranger-things-assets/images/marketplace/funko-pop-2.jpg",
    storeName: "Collector's Realm",
    storeIcon: "👾",
    rating: 5.0,
    reviews: 203,
    href: "/m/marketplace/vehicles",
  },
  {
    id: "st-toy-4",
    type: "marketplace",
    title: "LEGO Stranger Things Creel House MOC - Custom Build",
    groupName: "Facebook Marketplace",
    description: "Custom LEGO Creel House from Season 4. Incredible detail including the grandfather clock and attic. Over 2,500 pieces!",
    price: "$349",
    originalPrice: "$399",
    discount: "12% OFF",
    location: "Seattle, WA",
    nearbyDistance: "3 mi",
    image: "/images/stranger-things-assets/images/marketplace/lego-creel-house.jpg",
    storeName: "Upside Down Bricks",
    storeIcon: "🏚️",
    rating: 5.0,
    reviews: 42,
    href: "/m/marketplace/vehicles",
  },
  {
    id: "st-toy-5",
    type: "marketplace",
    title: "Stranger Things Funko Pop Set - Hawkins Gang Complete",
    groupName: "Facebook Marketplace",
    description: "Complete set of 6 Funko Pops: Mike, Dustin, Lucas, Will, Eleven, and Max. All mint in box. Selling as set only.",
    price: "$129",
    originalPrice: "$150",
    discount: "14% OFF",
    location: "Seattle, WA",
    nearbyDistance: null,
    image: "/images/stranger-things-assets/images/marketplace/funko-pop-3.jpg",
    storeName: "Pop Culture Palace",
    storeIcon: "👥",
    rating: 4.8,
    reviews: 67,
    href: "/m/marketplace/vehicles",
  },
];

// Used items for "Stranger Things Toys for sale" section - matches first 2 results on landing page
export const usedBikesResults = [
  {
    id: "t1",
    type: "marketplace",
    title: "Funko Pop Eleven with Eggos #421",
    price: "$25",
    location: "Seattle, WA",
    nearbyDistance: "1 mi",
    image: "/images/stranger-things-assets/images/marketplace/funko-pop.jpg",
    href: "/m/marketplace/t1",
  },
  {
    id: "t2", 
    type: "marketplace",
    title: "LEGO The Upside Down 75810",
    price: "$89",
    location: "Seattle, WA",
    nearbyDistance: "2 mi",
    image: "/images/stranger-things-assets/images/marketplace/lego.jpg",
    href: "/m/marketplace/t2",
  },
];

// Marketplace filter categories
export const marketplaceFilters = [
  { id: "funko", name: "Funko Pops", icon: "📦" },
  { id: "lego", name: "LEGO Sets", icon: "🧱" },
  { id: "collectibles", name: "Collectibles", icon: "🎭" },
  { id: "figures", name: "Action Figures", icon: "🎯" },
  { id: "games", name: "Games & Puzzles", icon: "🎲" },
  { id: "plush", name: "Plush Toys", icon: "🧸" },
];

export const marketplaceQuery = "stranger things toys";
