// Topics data for the search experience
// Each topic contains: search query, AI overview, search results, group post data, and related answers

export const topicsData = {
  coffee: {
    id: "coffee",
    label: "Coffee shops in Portland",
    searchQuery: "cafes in portland maine recommendations",
    postTitle: "What are the best cafes in Portland, Maine?",
    aiOverview: {
      summary: `For top-rated cafes in Portland, Maine, consider Coveside Coffee, Proper Cup, Yordprom Coffee, and Coffee by Design on Diamond St. Other great options include LB Kitchen and Coffee Me Up on Commercial Street.`,
      expandedText: `Coffee by Design is a popular choice with large seating areas, good wifi, and a convenient location. Many locals recommend exploring the East End and Old Port areas for the best cafe experiences.`,
    },
    groupData: {
      groupName: "Portland, Maine Community",
      groupAvatar: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=80&h=80&fit=crop",
      memberCount: "45.2K members",
      postBody: `Hi everyone! I just moved to Portland and I'm a huge coffee lover ☕

I work remotely so I'm looking for cafes with good wifi, great coffee, and a nice atmosphere to work from. Bonus points if they have outdoor seating for warmer days! Any recommendations would be greatly appreciated.`,
      postAuthor: {
        name: "Emily Chen",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&crop=faces",
      },
    },
    searchResults: [
      {
        id: "result-1",
        postId: "post-coffee-1",
        commentsCount: 21,
        timeAgo: "2 days ago",
        title: "What are the best cafes in Portland, Maine?",
        description: "Hi everyone! I just moved to Portland and I'm a huge coffee lover. I work remotely so I'm looking for cafes with good wifi, great coffee, and a nice atmosphere to work from...",
        comments: [
          { text: "Coveside, Proper Cup, Yordprom, Uncharted, Coffee by Design on Diamond St", reactions: 18, isTopComment: true },
          { text: "LB Kitchen!", reactions: 12, isTopComment: false },
          { text: "Coffee Me Up, Commercial Street", reactions: 9, isTopComment: false },
          { text: "Bard Coffee, Tandem, and Coffee Me Up", reactions: 7, isTopComment: false },
          { text: "Speckled Ax is amazing! Two locations - Congress St and East End. Great atmosphere for working.", reactions: 14, isTopComment: false },
          { text: "Don't sleep on Arabica - they have a quiet upstairs area perfect for remote work!", reactions: 11, isTopComment: false },
          { text: "Tandem Coffee Roasters is a bit out of the way but SO worth it. Best pastries too!", reactions: 16, isTopComment: false },
          { text: "If you want outdoor seating, Forage Market has a lovely patio in nice weather 🌿", reactions: 8, isTopComment: false },
          { text: "Holy Donut for the experience! Amazing donuts, decent coffee. Cash only though!", reactions: 13, isTopComment: false },
          { text: "Piccolo on Middle Street - tiny but the espresso is incredible. Best cortado in town.", reactions: 10, isTopComment: false },
          { text: "Rise and Shine Cafe on Munjoy Hill has great breakfast sandwiches + good coffee combo ☀️", reactions: 7, isTopComment: false },
          { text: "Rosemont Market has surprisingly great coffee and you can grab groceries too!", reactions: 5, isTopComment: false },
          { text: "The Portland Public Market has several options - fun to explore!", reactions: 6, isTopComment: false },
          { text: "Woodland Farms Brewery does coffee in the mornings! Great vibe and transitions to beer later 🍺", reactions: 9, isTopComment: false },
          { text: "Aurora Provisions in the West End is lovely - cute neighborhood spot with great pastries.", reactions: 8, isTopComment: false },
          { text: "Yordprom is a hidden gem! Small but the quality is top notch.", reactions: 11, isTopComment: false },
          { text: "Locally Sauced is underrated - good food AND coffee plus outdoor seating in summer.", reactions: 6, isTopComment: false },
          { text: "Stonewall Kitchen Cafe in Old Port - beautiful space and excellent coffee.", reactions: 7, isTopComment: false },
          { text: "Pro tip: most places are busiest 8-10am. Go after 10:30 for quieter work time! 💡", reactions: 15, isTopComment: false },
          { text: "The East End has the best concentration of cafes - you can cafe hop all day!", reactions: 10, isTopComment: false },
          { text: "Welcome to Portland! You're going to love it here. The coffee scene is amazing ☕", reactions: 12, isTopComment: false },
        ],
      },
      {
        id: "result-2",
        postId: "post-coffee-2",
        commentsCount: 34,
        timeAgo: "5 days ago",
        title: "What are the top coworking spaces in Portland, Maine?",
        description: "Looking for a good coworking space with reliable wifi and day passes. I need a spot to work from a few days a week...",
        comments: [
          { text: "Cloudport is great. Can get day passes for desks or rent a small conference room.", reactions: 15, isTopComment: true },
          { text: "CoworkHERS is amazing!!!", reactions: 11, isTopComment: false },
          { text: "Centrl they have multiple locations in the Portland area and beyond.", reactions: 8, isTopComment: false },
          { text: "VIDA Coworking - they have two locations", reactions: 6, isTopComment: false },
          { text: "Rize CoWorking is newer but really nice facilities. Good for video calls.", reactions: 9, isTopComment: false },
          { text: "The wifi at Cloudport is incredibly fast - never had issues with video conferences.", reactions: 12, isTopComment: false },
          { text: "CoworkHERS has great community events too! Really supportive environment.", reactions: 10, isTopComment: false },
          { text: "I like VIDA because they have both private offices and open desk options.", reactions: 7, isTopComment: false },
          { text: "Centrl on Congress St is my favorite location - great natural light!", reactions: 8, isTopComment: false },
          { text: "Day passes at Cloudport are around $25-30 - pretty reasonable for the area.", reactions: 6, isTopComment: false },
          { text: "Some cafes work too if you don't need a formal space - Coffee by Design has good wifi.", reactions: 11, isTopComment: false },
          { text: "The library downtown is free and has decent wifi if you're on a budget!", reactions: 14, isTopComment: false },
          { text: "Working Well is great if you're in wellness/health field - cooperative space in South Portland.", reactions: 5, isTopComment: false },
          { text: "I've tried most of them - Cloudport has the best coffee machine 😂", reactions: 9, isTopComment: false },
          { text: "VIDA does a free trial day! Worth checking out before committing.", reactions: 8, isTopComment: false },
          { text: "The standing desks at Rize are really nice quality.", reactions: 6, isTopComment: false },
          { text: "CoworkHERS membership includes access to all their events and workshops.", reactions: 7, isTopComment: false },
          { text: "Parking is easiest at Centrl - they have a lot nearby.", reactions: 5, isTopComment: false },
          { text: "I switched from WeWork to Cloudport and never looked back. Much better vibe.", reactions: 10, isTopComment: false },
          { text: "The phone booths at VIDA are great for private calls.", reactions: 6, isTopComment: false },
          { text: "Pro tip: visit a few on free trial days before deciding!", reactions: 11, isTopComment: false },
          { text: "Cloudport community is really collaborative - made some great connections there.", reactions: 8, isTopComment: false },
          { text: "Some spaces offer evening/weekend access which is clutch for side projects.", reactions: 7, isTopComment: false },
          { text: "The kitchen at Centrl is well-stocked. Free coffee and snacks!", reactions: 9, isTopComment: false },
          { text: "I work from different spots depending on my mood - variety is nice!", reactions: 6, isTopComment: false },
          { text: "VIDA South Portland location has better parking than downtown one.", reactions: 5, isTopComment: false },
          { text: "Meeting room rates at Cloudport are reasonable for client meetings.", reactions: 7, isTopComment: false },
          { text: "The outdoor patio at Centrl is amazing in summer!", reactions: 10, isTopComment: false },
          { text: "CoworkHERS founder is so welcoming - really created a special community.", reactions: 12, isTopComment: false },
          { text: "I've been a member at Cloudport for 2 years - highly recommend! 🙌", reactions: 13, isTopComment: false },
          { text: "The printing facilities at VIDA are included in membership which is handy.", reactions: 6, isTopComment: false },
          { text: "Rize has great ergonomic chairs - important if you're there all day!", reactions: 8, isTopComment: false },
          { text: "Some spaces offer mail service too if you need a business address.", reactions: 5, isTopComment: false },
          { text: "Welcome to the Portland coworking scene! You'll find your spot 👍", reactions: 9, isTopComment: false },
        ],
      },
      {
        id: "result-3",
        postId: "post-coffee-3",
        commentsCount: 28,
        timeAgo: "1 week ago",
        title: "What are the best places to work remotely in Portland, Maine?",
        description: "New to remote work and looking for spots with good atmosphere and reliable wifi. Coffee shops, coworking spaces, or anywhere really...",
        comments: [
          { text: "Cloudport is great. Can get day passes for desks or rent a small conference room.", reactions: 22, isTopComment: true },
          { text: "Rigby Yard has a million tables and cozy corners to camp out in during the day and great coffee", reactions: 14, isTopComment: false },
          { text: "Coveside Coffee, Uncharted, and Coffee by Design on Diamond Street are great spots.", reactions: 10, isTopComment: false },
          { text: "Rising Tide Brewing has free WiFi, good food, and non-alcoholic options.", reactions: 8, isTopComment: false },
          { text: "The library is underrated! Free wifi, quiet, and no pressure to buy anything.", reactions: 16, isTopComment: false },
          { text: "Arabica upstairs is my secret spot - rarely crowded and super quiet for focus work.", reactions: 12, isTopComment: false },
          { text: "Speckled Ax Congress St location has great wifi and plenty of outlets.", reactions: 9, isTopComment: false },
          { text: "Tandem has limited seating but the wifi is solid and coffee is incredible.", reactions: 7, isTopComment: false },
          { text: "I rotate between 3-4 spots depending on my mood and what kind of work I'm doing.", reactions: 11, isTopComment: false },
          { text: "For video calls, nothing beats a proper coworking space with phone booths.", reactions: 10, isTopComment: false },
          { text: "Forage Market is great but can get loud during lunch rush. Go early!", reactions: 6, isTopComment: false },
          { text: "Some hotels have lobby cafes that are quiet during weekdays - worth exploring!", reactions: 5, isTopComment: false },
          { text: "The East End has the best density of work-friendly cafes.", reactions: 13, isTopComment: false },
          { text: "Woodland Farms is unique - coffee in morning, beer in afternoon! Best of both worlds 🍺☕", reactions: 15, isTopComment: false },
          { text: "Portland Food Co-op has a small seating area - quiet and good coffee!", reactions: 4, isTopComment: false },
          { text: "I've tried working from bars in the afternoon - some have surprisingly good wifi!", reactions: 7, isTopComment: false },
          { text: "Definitely check speeds before settling in - not all cafes have reliable wifi.", reactions: 9, isTopComment: false },
          { text: "The Portland Public Market has multiple options - nice to switch spots throughout day.", reactions: 6, isTopComment: false },
          { text: "Pro tip: always scope out outlet availability before ordering! 🔌", reactions: 14, isTopComment: false },
          { text: "I made a spreadsheet of all the remote work spots with wifi speeds lol", reactions: 18, isTopComment: false },
          { text: "Coffee by Design has the most outlets I've found - never have to fight for one.", reactions: 8, isTopComment: false },
          { text: "Some spots have better morning vibes, others better afternoon. Experiment!", reactions: 7, isTopComment: false },
          { text: "The background noise level matters too - some places are too quiet or too loud.", reactions: 6, isTopComment: false },
          { text: "I bring noise-canceling headphones everywhere now. Game changer!", reactions: 11, isTopComment: false },
          { text: "Portland is honestly one of the best cities for remote work. So many options!", reactions: 12, isTopComment: false },
          { text: "If you find a good spot, tip well and they'll remember you! ☕💰", reactions: 9, isTopComment: false },
          { text: "Welcome to remote work life in Portland! You'll love it here 🙌", reactions: 10, isTopComment: false },
          { text: "The community of remote workers here is great - you'll make friends at cafes!", reactions: 8, isTopComment: false },
        ],
      },
    ],
    relatedAnswers: [
      {
        id: "qa-1",
        question: "What are the best cafes in Portland, Maine?",
        answer: "Portland, Maine, has a vibrant coffee scene with numerous cafes offering great coffee and atmosphere.",
        bullets: [
          "Coveside, Proper Cup, Yordprom, Uncharted, Coffee by Design on Diamond St",
          "LB Kitchen!",
          "Coffee Me Up, Commercial Street",
          "Bard Coffee, Tandem, and Coffee Me Up",
        ],
      },
      {
        id: "qa-2",
        question: "What are the top coworking spaces in Portland, Maine?",
        answer: "The top coworking spaces in Portland, Maine, include Cloudport, CoworkHERS, Centrl, VIDA Coworking, and Rize CoWorking & Collaboration Space.",
        bullets: [
          "Cloudport is great. Can get day passes for desks or rent a small conference room.",
          "CoworkHERS is amazing!!!",
          "Centrl they have multiple locations in the Portland area and beyond.",
          "VIDA Coworking - they have two locations",
        ],
      },
      {
        id: "qa-3",
        question: "What are the best places to work remotely in Portland, Maine?",
        answer: "Popular remote work spots in Portland, Maine, include coworking spaces, coffee shops, and breweries with good WiFi and amenities.",
        bullets: [
          "Cloudport is great. Can get day passes for desks or rent a small conference room.",
          "Rigby Yard has a million tables and cozy corners to camp out in during the day and great coffee",
          "Coveside Coffee, Uncharted, and Coffee by Design on Diamond Street are great spots.",
          "Rising Tide Brewing has free WiFi, good food, and non-alcoholic options.",
        ],
      },
    ],
    comments: [
      {
        author: { name: "Mike Richardson", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=64&h=64&fit=crop&crop=faces" },
        text: "Welcome to Portland! You're going to love the coffee scene here. I've been living here for 5 years and still discovering new spots.\n\nMy best advice is to explore the East End and Old Port areas - tons of great options within walking distance of each other.",
        reactions: 18,
      },
      {
        author: { name: "Jessica Torres", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=64&h=64&fit=crop&crop=faces" },
        text: "If you work remotely, definitely look for places with good wifi AND outlets. Some of the cozier spots can be hit or miss with power access!",
        reactions: 12,
      },
      {
        author: { name: "David Park", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=64&h=64&fit=crop&crop=faces" },
        text: "Pro tip: most cafes here are busiest between 8-10am on weekdays. If you want a quiet spot to work, try going after 10:30 or in the early afternoon!",
        reactions: 15,
      },
    ],
    serp: {
      entityCard: {
        name: "Coffee by Design",
        category: "Local coffee shop",
        followers: "18K followers",
        profileImage: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=120&h=120&fit=crop",
        photos: [
          "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=200&h=200&fit=crop",
          "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=200&h=200&fit=crop",
          "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=200&h=200&fit=crop",
        ],
      },
      contentGrid: [
        { author: "Emily Chen", timeAgo: "2h", reactions: "1.2K", imageUrl: "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=400&h=600&fit=crop" },
        { author: "Marcus Webb", timeAgo: "5h", reactions: "847", imageUrl: "https://images.unsplash.com/photo-1521302200778-33500795e128?w=400&h=600&fit=crop" },
        { author: "Priya Nair", timeAgo: "1d", reactions: "2.3K", imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=600&fit=crop" },
        { author: "Jordan Lee", timeAgo: "3d", reactions: "614", imageUrl: "https://images.unsplash.com/photo-1511537190424-bbbab87ac5eb?w=400&h=600&fit=crop" },
      ],
    },
  },

  turkey: {
    id: "turkey",
    label: "Cooking a 30lb turkey",
    searchQuery: "how long to cook 30lb turkey",
    postTitle: "How long should I cook a 30lb turkey for?",
    aiOverview: {
      summary: `For a 30lb turkey, plan for approximately 5.5-6.5 hours of cooking time at 325°F. The general rule is 13-15 minutes per pound for an unstuffed turkey.`,
      expandedText: `Many experienced cooks recommend starting at a higher temperature (425-450°F) for the first 30 minutes to brown the skin, then reducing to 325-350°F. Always use a meat thermometer to ensure the internal temperature reaches 165°F.`,
    },
    groupData: {
      groupName: "Home Cooking Enthusiasts",
      groupAvatar: "https://images.unsplash.com/photo-1574672280600-4accfa5b6f98?w=80&h=80&fit=crop",
      memberCount: "128K members",
      postBody: `Hey fellow cooks! 🦃

I'm hosting Thanksgiving this year and somehow ended up with a massive 30lb turkey! I've never cooked one this big before and I'm a bit nervous. How long should I cook it for? Any tips for keeping it moist would be greatly appreciated!`,
      postAuthor: {
        name: "Sarah Martinez",
        avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&h=80&fit=crop&crop=faces",
      },
    },
    searchResults: [
      {
        id: "result-1",
        postId: "post-turkey-1",
        commentsCount: 47,
        timeAgo: "3 days ago",
        title: "How long to cook a large turkey in a home oven?",
        description: "Hey fellow cooks! I'm hosting Thanksgiving this year and somehow ended up with a massive 30lb turkey! I've never cooked one this big before...",
        comments: [
          { text: "Roast the turkey in the preheated oven for approximately 13-15 minutes per pound (for a 12-14 lb turkey, this will be about 3 to 3 1/2 hours).", reactions: 34, isTopComment: true },
          { text: "Approximate Cooking Timing: 10-13 lbs. = 50 minutes to 1 1/4 hrs. 13-16 lbs. = 1 1/4 hrs to 1 hour 50 minutes. 16-19 lbs. = 1 1/2 hrs to 2 hrs.", reactions: 28, isTopComment: false },
          { text: "For a 17.7 lb turkey, some recommended 4.5 hours at 350°F, while others suggested cooking to an internal temperature of 165°F.", reactions: 22, isTopComment: false },
          { text: "A meat thermometer is your best friend! Internal temp of 165°F in the thickest part of the thigh.", reactions: 31, isTopComment: false },
          { text: "For a 30 pounder, you're looking at roughly 5.5-6.5 hours at 325°F unstuffed.", reactions: 26, isTopComment: false },
          { text: "Don't forget to let it rest for at least 30 minutes before carving! The juices need to redistribute. 🦃", reactions: 29, isTopComment: false },
          { text: "I always add an hour buffer to my cooking time just in case. Better to have it done early and keep it warm.", reactions: 18, isTopComment: false },
          { text: "Pro tip: take the turkey out of the fridge 1-2 hours before cooking to bring it to room temp.", reactions: 24, isTopComment: false },
          { text: "If you're stuffing it, add another 30-45 minutes to cooking time.", reactions: 15, isTopComment: false },
          { text: "The pop-up thermometer that comes with some turkeys is unreliable. Always use your own thermometer!", reactions: 21, isTopComment: false },
          { text: "I've been cooking turkeys for 20 years - trust the thermometer, not the clock.", reactions: 33, isTopComment: false },
          { text: "Start checking temp about an hour before you expect it to be done. Every oven is different!", reactions: 17, isTopComment: false },
          { text: "Make sure your oven is actually at the right temp - use an oven thermometer to verify.", reactions: 14, isTopComment: false },
          { text: "For a bird that big, consider spatchcocking - cuts cooking time significantly!", reactions: 19, isTopComment: false },
          { text: "Tent with foil if the skin is getting too brown before it's cooked through.", reactions: 16, isTopComment: false },
          { text: "I always put aromatics in the cavity - onion, celery, herbs. Doesn't affect time but adds flavor!", reactions: 12, isTopComment: false },
          { text: "Remember the temperature will rise 5-10 degrees while resting. Pull it at 160°F.", reactions: 27, isTopComment: false },
          { text: "A 30lb turkey is huge! Make sure it actually fits in your oven before Thanksgiving day 😅", reactions: 38, isTopComment: false },
          { text: "The dark meat needs to reach a higher temp than breast meat - that's the tricky part.", reactions: 13, isTopComment: false },
          { text: "Electric roasters are great for big birds if your oven is too small!", reactions: 11, isTopComment: false },
          { text: "Start early! Nothing worse than hungry guests waiting for the turkey.", reactions: 20, isTopComment: false },
          { text: "I rotate the pan halfway through for even browning.", reactions: 9, isTopComment: false },
          { text: "Good luck! Your first big turkey is nerve-wracking but you've got this! 🙌", reactions: 25, isTopComment: false },
          { text: "Don't open the oven door too often - you lose heat every time!", reactions: 22, isTopComment: false },
          { text: "Write down what you do this year so you can improve next year!", reactions: 16, isTopComment: false },
          { text: "The Butterball hotline is actually really helpful if you get stuck!", reactions: 14, isTopComment: false },
          { text: "Saved this post for Thursday! Thanks everyone for the tips 🦃", reactions: 31, isTopComment: false },
        ],
      },
      {
        id: "result-2",
        postId: "post-turkey-2",
        commentsCount: 31,
        timeAgo: "1 week ago",
        title: "Best temperature for roasting a 30lb turkey?",
        description: "What's the ideal oven temperature for a big bird? I've seen so many different recommendations online...",
        comments: [
          { text: "Rip that oven to 450 for 30 min. Then cover the breast with foil and bake at 350° until probe hits 161°. Pull and let rest it will come to 165°. Perfect every time.", reactions: 25, isTopComment: true },
          { text: "I use an electric roaster every year. I put it as high as it will for 30 min and then 350 for how ever long it takes for the weight of your turkey.", reactions: 18, isTopComment: false },
          { text: "I usually do 450 for first hour. Then lower temp to 350-375. add half hour or so if stuffed.", reactions: 15, isTopComment: false },
          { text: "A common approach is to roast at 425°F for the first 30 minutes, then reduce heat to 350°F.", reactions: 12, isTopComment: false },
          { text: "The high-then-low method gives you crispy skin without overcooking the meat. Game changer!", reactions: 21, isTopComment: false },
          { text: "325°F the whole time is the safest bet if you're nervous. Takes longer but hard to mess up.", reactions: 14, isTopComment: false },
          { text: "I've tried both methods - high start definitely gives better skin texture.", reactions: 17, isTopComment: false },
          { text: "Convection if you have it! Reduces cooking time by about 25%.", reactions: 19, isTopComment: false },
          { text: "Make sure your oven is calibrated. My oven runs 25 degrees hot!", reactions: 11, isTopComment: false },
          { text: "The foil tent on the breast is KEY once it starts browning too much.", reactions: 16, isTopComment: false },
          { text: "I did 500°F for 20 min once - amazing skin but watch it carefully!", reactions: 13, isTopComment: false },
          { text: "Position the rack in the lower third of the oven for best results.", reactions: 10, isTopComment: false },
          { text: "Breast side up the whole time? Or do you flip? Curious what works best.", reactions: 8, isTopComment: false },
          { text: "Never flip! Just tent with foil. Flipping a hot 30lb turkey is dangerous 😬", reactions: 22, isTopComment: false },
          { text: "Some people start breast-side down then flip halfway. I'm too scared to try lol", reactions: 9, isTopComment: false },
          { text: "The pan matters too - dark pans absorb more heat and can burn the bottom.", reactions: 12, isTopComment: false },
          { text: "Add a cup of water or broth to the pan to prevent drippings from burning.", reactions: 15, isTopComment: false },
          { text: "Pro tip: save those drippings for the best gravy ever! 🤤", reactions: 24, isTopComment: false },
          { text: "Whatever temp you choose, just trust your thermometer over any timing chart.", reactions: 20, isTopComment: false },
          { text: "I've been doing this 15 years - the high-low method is my go-to. Never fails!", reactions: 18, isTopComment: false },
          { text: "Good luck! Post pics when it's done! 🦃", reactions: 11, isTopComment: false },
        ],
      },
      {
        id: "result-3",
        postId: "post-turkey-3",
        commentsCount: 52,
        timeAgo: "2 weeks ago",
        title: "How to ensure a juicy turkey roast?",
        description: "Every year my turkey comes out dry. Looking for foolproof methods to keep a large bird moist and delicious...",
        comments: [
          { text: "Brine it and make sure you baste it every hour at least", reactions: 42, isTopComment: true },
          { text: "The night before I take butter with herbs like rosemary, time and garlic and mix well. Then I put the butter under the skin", reactions: 35, isTopComment: false },
          { text: "Use a meat thermometer and dont overcook it", reactions: 28, isTopComment: false },
          { text: "Don't Overcook: Use a meat thermometer to ensure accurate cooking. Baste Regularly: Basting helps keep the turkey moist. Let it Rest: Allow the turkey to rest before carving for juicier meat.", reactions: 22, isTopComment: false },
          { text: "Brining is the #1 thing that changed my turkey game. Wet or dry brine both work!", reactions: 38, isTopComment: false },
          { text: "Dry brine = salt and leave uncovered in fridge overnight. Crispier skin than wet brine!", reactions: 31, isTopComment: false },
          { text: "Compound butter under the skin is EVERYTHING. Garlic, herbs, lemon zest... so good!", reactions: 29, isTopComment: false },
          { text: "The biggest mistake is overcooking. Pull it at 160°F and let carryover do the rest.", reactions: 33, isTopComment: false },
          { text: "Mayo on the skin! Sounds weird but gives you incredible crispy golden skin.", reactions: 26, isTopComment: false },
          { text: "I inject mine with melted butter and broth. Moisture from the inside out!", reactions: 24, isTopComment: false },
          { text: "Cheesecloth soaked in butter draped over the breast keeps it super moist.", reactions: 21, isTopComment: false },
          { text: "Spatchcocking = flatter bird = faster cooking = less chance of drying out!", reactions: 27, isTopComment: false },
          { text: "REST REST REST. At least 30 minutes, tented loosely with foil. Don't skip this!", reactions: 36, isTopComment: false },
          { text: "The drippings are where all the flavor went. Make gravy and pour it on!", reactions: 19, isTopComment: false },
          { text: "I flip mine breast-side down for the first half. The dark meat bastes the breast.", reactions: 17, isTopComment: false },
          { text: "Stuffing absorbs moisture from the bird. Cook dressing separately for juicier turkey.", reactions: 23, isTopComment: false },
          { text: "My grandmother swore by putting the turkey in a paper bag. Old school but works!", reactions: 14, isTopComment: false },
          { text: "Bacon lattice on top = basting + flavor. You're welcome. 🥓", reactions: 32, isTopComment: false },
          { text: "Ice packs on the breast while it comes to room temp. Evens out cooking time.", reactions: 16, isTopComment: false },
          { text: "Fresh turkey > frozen turkey for moisture. Worth the extra cost!", reactions: 20, isTopComment: false },
          { text: "Heritage breeds are pricier but so much more flavorful and naturally moist.", reactions: 15, isTopComment: false },
          { text: "Don't open the oven constantly to check. Every time you lose heat and moisture.", reactions: 25, isTopComment: false },
          { text: "Roasting bag keeps moisture in but you sacrifice crispy skin. Trade-off.", reactions: 13, isTopComment: false },
          { text: "I've tried everything - brining + butter under skin + not overcooking is the winning combo.", reactions: 39, isTopComment: false },
          { text: "White wine in the roasting pan adds moisture and makes amazing gravy base.", reactions: 18, isTopComment: false },
          { text: "Carve against the grain and slice thin. Makes even slightly dry turkey seem juicy!", reactions: 12, isTopComment: false },
          { text: "Electric knife is a game changer for clean slices that hold moisture.", reactions: 11, isTopComment: false },
          { text: "This thread is gold! Saving all of this for Thursday 🦃", reactions: 28, isTopComment: false },
          { text: "I tried the butter under skin method last year after seeing it here - best turkey ever!", reactions: 34, isTopComment: false },
          { text: "Good luck everyone! May your turkeys be juicy and your gravy smooth! 🍽️", reactions: 22, isTopComment: false },
        ],
      },
    ],
    relatedAnswers: [
      {
        id: "qa-1",
        question: "How long to cook a large turkey in a home oven?",
        answer: "The cooking time for a large turkey in a home oven varies based on the turkey's size and oven temperature, but general guidelines suggest 13-15 minutes per pound at 325°F.",
        bullets: [
          "Roast the turkey in the preheated oven for approximately 13-15 minutes per pound (for a 12-14 lb turkey, this will be about 3 to 3 1/2 hours).",
          "Approximate Cooking Timing: 10-13 lbs. = 50 minutes to 1 1/4 hrs. 13-16 lbs. = 1 1/4 hrs to 1 hour 50 minutes. 16-19 lbs. = 1 1/2 hrs to 2 hrs.",
          "For a 17.7 lb turkey, some recommended 4.5 hours at 350°F, while others suggested cooking to an internal temperature of 165°F.",
        ],
      },
      {
        id: "qa-2",
        question: "Best temperature for roasting a 30lb turkey?",
        answer: "For roasting a 30lb turkey, a common temperature approach is to start at a high heat, around 425-450°F, for the first 30 minutes, then reduce the temperature to 325-350°F until the turkey is done.",
        bullets: [
          "Rip that oven to 450 for 30 min. Then cover the breast with foil and bake at 350° until probe hits 161°. Pull and let rest it will come to 165°. Perfect every time.",
          "I use an electric roaster every year. I put it as high as it will for 30 min and then 350 for how ever long it takes for the weight of your turkey.",
          "I usually do 450 for first hour. Then lower temp to 350-375. add half hour or so if stuffed.",
          "A common approach is to roast at 425°F for the first 30 minutes, then reduce heat to 350°F.",
        ],
      },
      {
        id: "qa-3",
        question: "How to ensure a juicy turkey roast?",
        answer: "To ensure a juicy turkey roast, it's essential to follow a combination of preparation and cooking techniques.",
        bullets: [
          "Brine it and make sure you baste it every hour at least",
          "The night before I take butter with herbs like rosemary, time and garlic and mix well. Then I put the butter under the skin",
          "Use a meat thermometer and dont overcook it",
          "Don't Overcook: Use a meat thermometer to ensure accurate cooking. Baste Regularly: Basting helps keep the turkey moist. Let it Rest: Allow the turkey to rest before carving for juicier meat.",
        ],
      },
      {
        id: "qa-4",
        question: "Turkey cooking time calculator",
        answer: "To determine the cooking time for a turkey, consider the weight of the bird and whether it's stuffed or unstuffed.",
        bullets: [
          "As a general rule: 13 minutes per pound of turkey, internal temperature will be 165F.",
          "For an unstuffed turkey, estimate cooking time based on weight, approximately 15 minutes per pound (33 minutes per kg).",
          "10 to 18 pounds: 3 to 3-1/2 hours (unstuffed), 3-3/4 to 4-1/2 hours (stuffed)",
          "Cooking times are generally done per pound if a thermometer isn't available. 15-20 min/lb.",
        ],
      },
      {
        id: "qa-5",
        question: "Safe internal temperature for cooked turkey?",
        answer: "The safe internal temperature for cooked turkey is at least 165°F, measured at the thickest part of the thigh, breast, and stuffing if applicable.",
        bullets: [
          "make sure that your turkey or chicken or duck is cooked to at least 165°. Internal temperature at the thickest part of the thigh.",
          "Whole turkey: On your meat thermometer, a whole cooked turkey should reach an internal temperature of 165°F in the breast, and 175°F in the thigh.",
          "For safety and doneness, check the internal temperature of the turkey and stuffing with a food thermometer.",
          "removed from brine and cooked in a 375d preheated oven for 30-35 minutes until browned and internal temperature was 165 in the thickest part of the thigh.",
        ],
      },
    ],
    comments: [
      {
        author: { name: "Chef Antonio", avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=64&h=64&fit=crop&crop=faces" },
        text: "For a 30lb bird, you're looking at about 5.5-6.5 hours at 325°F. But PLEASE use a meat thermometer - that's the only way to know for sure it's done!",
        reactions: 34,
      },
      {
        author: { name: "Grandma Betty", avatar: "https://images.unsplash.com/photo-1566616213894-2d4e1baee5d8?w=64&h=64&fit=crop&crop=faces" },
        text: "Brine it overnight! Game changer for keeping it moist. I use a simple salt and sugar brine with herbs.",
        reactions: 28,
      },
      {
        author: { name: "Tom Wilson", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=64&h=64&fit=crop&crop=faces" },
        text: "Start at 450°F for 30 minutes to get that beautiful golden skin, then drop to 325°F for the rest. Works every time!",
        reactions: 22,
      },
    ],
  },

  nfl: {
    id: "nfl",
    label: "Streaming NFL games online",
    searchQuery: "alternatives to streameast for sports streaming",
    postTitle: "What are some alternatives to StreamEast as a streaming service for sports?",
    aiOverview: {
      summary: `Several alternatives to StreamEast are available for streaming NFL games, including official services like NFL+, YouTube TV, Peacock, and Amazon Prime Video, as well as free options like Sportsurge and Dofu Sports app.`,
      expandedText: `YouTube TV is often recommended as the most comprehensive option, though it requires a subscription. For free alternatives, users frequently mention Sportsurge, Methstreams, and Dofu Sports, though these may have reliability issues and ads.`,
    },
    groupData: {
      groupName: "NFL Fans & Fantasy Football",
      groupAvatar: "https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=80&h=80&fit=crop",
      memberCount: "892K members",
      postBody: `Hey everyone! 🏈

StreamEast has been super unreliable lately and I'm tired of dealing with all the popups. What are some good alternatives for streaming NFL games? I don't mind paying for something if it actually works consistently. Would love to hear what you all are using!`,
      postAuthor: {
        name: "Marcus Johnson",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=faces",
      },
    },
    searchResults: [
      {
        id: "result-1",
        postId: "post-nfl-1",
        commentsCount: 156,
        timeAgo: "1 day ago",
        title: "Can I stream NFL games online?",
        description: "StreamEast has been super unreliable lately and I'm tired of dealing with all the popups. What are some good alternatives for streaming NFL games?",
        comments: [
          { text: "NFL games are coming to streaming services like Prime, Netflix, Peacock, ESPN+, NFL+, NFL Sunday Ticket & YouTube this season", reactions: 87, isTopComment: true },
          { text: "YouTube TV is the only option as far as I know", reactions: 64, isTopComment: false },
          { text: "Streameast is what I use for everything.", reactions: 45, isTopComment: false },
          { text: "NFL +", reactions: 38, isTopComment: false },
          { text: "Peacock has some games for free! Check which ones are exclusive there.", reactions: 52, isTopComment: false },
          { text: "Amazon Prime has Thursday Night Football - included with Prime membership!", reactions: 61, isTopComment: false },
          { text: "YouTube TV is pricey but honestly worth it for all the channels you get.", reactions: 43, isTopComment: false },
          { text: "NFL+ is like $7/month but you can only watch on mobile/tablet. Good for commuting!", reactions: 36, isTopComment: false },
          { text: "Local games are free over the air with an antenna! Old school but works 📺", reactions: 48, isTopComment: false },
          { text: "Sunday Ticket on YouTube is your only legal option for out-of-market games.", reactions: 39, isTopComment: false },
          { text: "I split Sunday Ticket with 3 friends. Much more affordable that way.", reactions: 55, isTopComment: false },
          { text: "Check if you qualify for the student discount on Sunday Ticket - huge savings!", reactions: 33, isTopComment: false },
          { text: "Fubo is another option if you need regional sports networks too.", reactions: 28, isTopComment: false },
          { text: "Some bars have NFL Sunday Ticket - grab some wings and watch there! 🍗", reactions: 41, isTopComment: false },
          { text: "The NFL app is free for local games and primetime games on mobile.", reactions: 31, isTopComment: false },
          { text: "Netflix is getting some Christmas games this year! First time ever.", reactions: 67, isTopComment: false },
          { text: "Hulu + Live TV also has all the major networks for NFL games.", reactions: 25, isTopComment: false },
          { text: "VPN + international streaming is how I watch. Games are often free in other countries.", reactions: 58, isTopComment: false },
          { text: "ESPN+ has some games but it's inconsistent which ones.", reactions: 22, isTopComment: false },
          { text: "The legal options have gotten SO much better in the last few years honestly.", reactions: 34, isTopComment: false },
          { text: "Just wish they'd put everything in one place instead of 10 different services 😤", reactions: 89, isTopComment: false },
          { text: "RedZone is a must if you play fantasy! YouTube TV includes it.", reactions: 47, isTopComment: false },
          { text: "Thanks for all the suggestions everyone! Finally cutting cable this season 🙌", reactions: 29, isTopComment: false },
        ],
      },
      {
        id: "result-2",
        postId: "post-nfl-2",
        commentsCount: 89,
        timeAgo: "3 days ago",
        title: "What are the best alternatives to StreamEast?",
        description: "I moved away from my home city but still want to watch my team. Sunday Ticket is so expensive! Any alternatives?",
        comments: [
          { text: "Try vpn and Sportsurge. They post a bunch of links.", reactions: 42, isTopComment: true },
          { text: "download the dofu app. Or even use crackstreamz", reactions: 35, isTopComment: false },
          { text: "Methstreams for the win", reactions: 28, isTopComment: false },
          { text: "Dofu is easy and free", reactions: 22, isTopComment: false },
          { text: "Sportsurge aggregates links from multiple sources - usually find a working one.", reactions: 38, isTopComment: false },
          { text: "NFLbite used to be good but they keep changing domains.", reactions: 31, isTopComment: false },
          { text: "Use an adblocker with any free streaming site. Makes it so much better.", reactions: 56, isTopComment: false },
          { text: "Buffstreams is another option. Quality varies by game.", reactions: 24, isTopComment: false },
          { text: "I use a VPN with DAZN. Get all the games in some countries for cheap!", reactions: 33, isTopComment: false },
          { text: "Dofu Sports app is legit the easiest. Just search for your game.", reactions: 47, isTopComment: false },
          { text: "Warning: some of these free sites are sketchy. Be careful what you click!", reactions: 29, isTopComment: false },
          { text: "I finally just paid for Sunday Ticket. Peace of mind is worth it for me.", reactions: 19, isTopComment: false },
          { text: "720pstreams works pretty well. Fewer popups than others.", reactions: 25, isTopComment: false },
          { text: "Cast from phone to TV for better viewing. Works with most streaming apps.", reactions: 21, isTopComment: false },
          { text: "Markky streams on Twitter/X sometimes have live games too.", reactions: 17, isTopComment: false },
          { text: "Reddit NFL streams was the best before they shut it down RIP 😭", reactions: 62, isTopComment: false },
          { text: "Weakstreams has been reliable for me this season.", reactions: 23, isTopComment: false },
          { text: "Just make sure you have good antivirus if using free sites!", reactions: 34, isTopComment: false },
          { text: "The quality on free streams has gotten way better tbh. 1080p sometimes!", reactions: 28, isTopComment: false },
          { text: "I rotate between a few sites depending on which is working that week.", reactions: 31, isTopComment: false },
          { text: "Thanks for all the alternatives! StreamEast has been so unreliable lately.", reactions: 26, isTopComment: false },
        ],
      },
      {
        id: "result-3",
        postId: "post-nfl-3",
        commentsCount: 67,
        timeAgo: "1 week ago",
        title: "Are there any free sports streaming services?",
        description: "Looking for free options to watch NFL games. Don't want to pay for cable or expensive subscriptions...",
        comments: [
          { text: "istreameast.app just gotta close the pop ups 2-3 times but after will work.", reactions: 35, isTopComment: true },
          { text: "Dofu sports", reactions: 28, isTopComment: false },
          { text: "StreamEast", reactions: 22, isTopComment: false },
          { text: "Pluto TV, tubi tv, peacock, freevee", reactions: 18, isTopComment: false },
          { text: "Tubi has some sports content but not live NFL games unfortunately.", reactions: 15, isTopComment: false },
          { text: "Pluto TV has NFL channel with classic games and highlights. Not live though.", reactions: 19, isTopComment: false },
          { text: "Peacock has some live games! Not all but worth checking the schedule.", reactions: 31, isTopComment: false },
          { text: "Local channels are FREE with an antenna. CBS, NBC, FOX all have NFL games!", reactions: 42, isTopComment: false },
          { text: "Yahoo Sports app streams local games for free on mobile.", reactions: 27, isTopComment: false },
          { text: "The NFL app itself streams local and primetime games free on mobile.", reactions: 33, isTopComment: false },
          { text: "Free trials of YouTube TV/Fubo during playoffs = big brain move 🧠", reactions: 45, isTopComment: false },
          { text: "Some libraries have free streaming services that include sports!", reactions: 14, isTopComment: false },
          { text: "Locast was amazing before it got shut down. RIP.", reactions: 21, isTopComment: false },
          { text: "Sports bars technically free if you nurse one drink all game 😂", reactions: 38, isTopComment: false },
          { text: "T-Mobile customers get free MLB.TV - wish they'd do NFL too!", reactions: 16, isTopComment: false },
          { text: "Crackstreams works but the popups are INSANE. Use adblocker!", reactions: 29, isTopComment: false },
          { text: "I just listen on the radio when I can't watch. Old school but free!", reactions: 12, isTopComment: false },
          { text: "Twitch sometimes has streamers showing games. Hit or miss though.", reactions: 17, isTopComment: false },
          { text: "Nothing truly free and legal for all games. That's just how NFL works 🤷", reactions: 36, isTopComment: false },
          { text: "Good luck! Hopefully one of these options works for you 🏈", reactions: 23, isTopComment: false },
        ],
      },
    ],
    relatedAnswers: [
      {
        id: "qa-1",
        question: "Can I stream NFL games online?",
        answer: "You can stream NFL games online through various services, including official platforms and third-party sites, although some may require a subscription or have regional restrictions.",
        bullets: [
          "NFL games are coming to streaming services like Prime, Netflix, Peacock, ESPN+, NFL+, NFL Sunday Ticket & YouTube this season",
          "YouTube TV is the only option as far as I know",
          "Streameast is what I use for everything.",
          "NFL +",
        ],
      },
      {
        id: "qa-2",
        question: "What are the best alternatives to StreamEast?",
        answer: "Several alternatives to StreamEast are recommended by users in Facebook Groups discussions, including Sportsurge, Methstreams, Dofu Sports app, and Buffstreams.",
        bullets: [
          "Try vpn and Sportsurge. They post a bunch of links.",
          "download the dofu app. Or even use crackstreamz",
          "Methstreams for the win",
          "Dofu is easy and free",
        ],
      },
      {
        id: "qa-3",
        question: "How to watch sports games out of state?",
        answer: "To watch sports games out of state, consider using streaming services or apps that offer live sports coverage.",
        bullets: [
          "If you are out of state, use MLB tv to stream!",
          "Fubo...some how I get ROOT SPORTS in El Paso",
          "I use MLBTV. They should have a pretty good discount since it is later in the season.",
          "YouTube TV has all of O State's games. This year there is a money dispute with YouTube and Fox who has the rights.",
        ],
      },
      {
        id: "qa-4",
        question: "Are there any free sports streaming services?",
        answer: "Some free sports streaming services are available, although their availability and reliability can vary.",
        bullets: [
          "istreameast.app just gotta close the pop ups 2-3 times but after will work.",
          "Dofu sports",
          "StreamEast",
          "Pluto TV, tubi tv, peacock, freevee",
        ],
      },
      {
        id: "qa-5",
        question: "What are the best sports streaming websites?",
        answer: "The best sports streaming websites recommended by Facebook Group users include FuboTV, YouTube TV, and various free streaming sites, although the latter may have reliability issues.",
        bullets: [
          "FuboTV subscription + ExpressVPN has allowed me to basically stream any sport from any region.",
          "Fubo has it all. Lot of sports.",
          "YouTube TV is awesome and the price is better than cable.",
          "Crackstreams, but download the AdGuard app, thank me later.",
        ],
      },
    ],
    comments: [
      {
        author: { name: "Jake Thompson", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=64&h=64&fit=crop&crop=faces" },
        text: "YouTube TV is honestly worth every penny. Never had buffering issues and you get all the channels for NFL games plus RedZone!",
        reactions: 87,
      },
      {
        author: { name: "Chris Davis", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=64&h=64&fit=crop&crop=faces" },
        text: "Dofu Sports app is free and works great. Just download it and search for the game you want. Way less sketchy than browser streaming sites.",
        reactions: 64,
      },
      {
        author: { name: "Mike Stevens", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=64&h=64&fit=crop&crop=faces" },
        text: "NFL+ is only $7/month and you get every game on your phone/tablet. Great for when you're not at home!",
        reactions: 45,
      },
    ],
  },

  pinecone: {
    id: "pinecone",
    label: "Pinecone centerpiece ideas",
    searchQuery: "pinecone centerpiece ideas DIY",
    postTitle: "Could you show me your pinecone centerpieces?",
    aiOverview: {
      summary: `Pinecone centerpieces are a popular DIY decoration, especially for fall and winter. Common ideas include filling clear vases with pinecones and candles, creating garlands, and combining them with gourds, leaves, and fairy lights.`,
      expandedText: `For best results, bake pinecones at low heat for 30 minutes to kill any bugs. Combine with elements like eucalyptus, mini pumpkins, and burlap ribbons for a rustic look.`,
    },
    groupData: {
      groupName: "DIY Home Decor Ideas",
      groupAvatar: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=80&h=80&fit=crop",
      memberCount: "567K members",
      postBody: `Hi everyone! 🎄🍂

I've collected SO many pinecones from my backyard and I want to make some beautiful centerpieces for Thanksgiving and Christmas. Could you show me your pinecone creations for inspiration? I'd love to see what you've all made!`,
      postAuthor: {
        name: "Amanda Collins",
        avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&h=80&fit=crop&crop=faces",
      },
    },
    searchResults: [
      {
        id: "result-1",
        postId: "post-pinecone-1",
        commentsCount: 234,
        timeAgo: "5 days ago",
        title: "What are some DIY ideas for pinecone decorations?",
        description: "I've collected SO many pinecones from my backyard and I want to make some beautiful centerpieces for Thanksgiving and Christmas...",
        comments: [
          { text: "Just glue the pinecones onto wood slices, add tiny ornaments, and top them with a star.", reactions: 156, isTopComment: true },
          { text: "Collect pinecones, paint or glitter them if desired, and stack them into a tree shape using hot glue or a cone base.", reactions: 98, isTopComment: false },
          { text: "I took a snowflake from the Dollar tree and hot glued my pinecones on them. You could also cut the snowflakes out of cardboard.", reactions: 76, isTopComment: false },
          { text: "String together pinecones and small branches to create a natural garland for your mantle, stair railing, or tree.", reactions: 54, isTopComment: false },
          { text: "Spray paint them gold or silver! Mix with natural ones for beautiful contrast ✨", reactions: 89, isTopComment: false },
          { text: "Make a wreath! Wire frame + hot glue + pinecones = gorgeous door decor 🎄", reactions: 72, isTopComment: false },
          { text: "Dip the tips in white paint to look like snow. So pretty for Christmas!", reactions: 65, isTopComment: false },
          { text: "Pinecone fire starters! Dip in melted wax - great gifts for fireplace owners.", reactions: 47, isTopComment: false },
          { text: "Fill a big glass jar with pinecones and fairy lights. Magical! ✨", reactions: 83, isTopComment: false },
          { text: "Make pinecone owls! Add felt wings and googly eyes - kids love making these.", reactions: 41, isTopComment: false },
          { text: "I bleach mine for a really unique pale look. Takes a few days but worth it!", reactions: 38, isTopComment: false },
          { text: "Cinnamon scented pinecones! Add cinnamon oil - makes the house smell amazing.", reactions: 91, isTopComment: false },
          { text: "Layer in a dough bowl with candles and eucalyptus. Instant centerpiece!", reactions: 67, isTopComment: false },
          { text: "Add to your Christmas tree! Just hot glue a ribbon loop for hanging.", reactions: 52, isTopComment: false },
          { text: "Make place card holders by cutting a slit in the top. Rustic and cute!", reactions: 44, isTopComment: false },
          { text: "Fill stockings with mini pinecones and cinnamon sticks - free and festive!", reactions: 36, isTopComment: false },
          { text: "Pinecone turkeys for the kids table at Thanksgiving! Pipe cleaner legs and felt feathers.", reactions: 58, isTopComment: false },
          { text: "Use as gift toppers instead of bows. Add a sprig of greenery too!", reactions: 49, isTopComment: false },
          { text: "Hot glue to a foam cone for an easy pinecone Christmas tree.", reactions: 61, isTopComment: false },
          { text: "The Dollar Store has great supplies for decorating pinecones cheap!", reactions: 55, isTopComment: false },
          { text: "Remember to bake them first to kill any bugs! 200°F for 30 min.", reactions: 78, isTopComment: false },
          { text: "I made a chandelier with fishing line and pinecones - so unique!", reactions: 34, isTopComment: false },
          { text: "These are all such great ideas! Saving this post 📌", reactions: 42, isTopComment: false },
        ],
      },
      {
        id: "result-2",
        postId: "post-pinecone-2",
        commentsCount: 178,
        timeAgo: "2 weeks ago",
        title: "How to create a beautiful fall centerpiece using pinecones?",
        description: "Want to decorate my Thanksgiving table but don't want to spend a fortune. Looking for natural, rustic ideas...",
        comments: [
          { text: "Fill your Clear Vase with pinecone's halfway, insert your Candle in the middle and continue adding remaining Cones to the top of vase.", reactions: 89, isTopComment: true },
          { text: "Gather Your Bounty: Look for vibrant fallen maple leaves, varying sizes of pinecones, textured acorns, dry seed pods, and small, knobby twigs or dried grass plumes.", reactions: 67, isTopComment: false },
          { text: "I glued 5 of them together into a star, secured them with a glued ribbon in the back to keep them connected.", reactions: 45, isTopComment: false },
          { text: "Don't forget to put them on a cookie tray and heat them for about 30 minutes on a low heat to kill any crawling critters and bacteria.", reactions: 34, isTopComment: false },
          { text: "Wooden cutting board + pillar candle + pinecones scattered around = instant elegance!", reactions: 72, isTopComment: false },
          { text: "Add some mini pumpkins and gourds for color variety 🎃", reactions: 58, isTopComment: false },
          { text: "Burlap table runner underneath ties the rustic look together.", reactions: 41, isTopComment: false },
          { text: "Mason jars with pinecones inside make great individual place settings.", reactions: 53, isTopComment: false },
          { text: "Lantern with pinecones and a candle inside - works for indoor or outdoor tables!", reactions: 62, isTopComment: false },
          { text: "Mix different sizes of pinecones for more visual interest.", reactions: 37, isTopComment: false },
          { text: "Add cinnamon sticks for scent AND visual appeal. Two birds one stone!", reactions: 48, isTopComment: false },
          { text: "Dried orange slices look beautiful with pinecones! Smells amazing too.", reactions: 56, isTopComment: false },
          { text: "Long wooden tray down the center of table, filled with all the things = gorgeous!", reactions: 69, isTopComment: false },
          { text: "Eucalyptus stems are cheap at Trader Joe's and look so pretty with pinecones.", reactions: 44, isTopComment: false },
          { text: "I love adding some dried wheat or grass for height variation.", reactions: 31, isTopComment: false },
          { text: "Spray some with matte gold for a touch of glamour!", reactions: 52, isTopComment: false },
          { text: "Berry branches (real or fake) add great pops of red color.", reactions: 39, isTopComment: false },
          { text: "Don't overcrowd - sometimes less is more with natural elements.", reactions: 46, isTopComment: false },
          { text: "Battery operated candles are safer if you're leaving it up all season.", reactions: 33, isTopComment: false },
          { text: "This is making me so excited for fall decorating! 🍂", reactions: 61, isTopComment: false },
        ],
      },
      {
        id: "result-3",
        postId: "post-pinecone-3",
        commentsCount: 145,
        timeAgo: "3 weeks ago",
        title: "What types of decorations go well with pinecones for a Thanksgiving theme?",
        description: "Planning my Thanksgiving table decor and want to incorporate the pinecones I collected. What pairs well with them?",
        comments: [
          { text: "White pumpkin or thick candle with fall foliage.", reactions: 72, isTopComment: true },
          { text: "Gourds, colorful leaves, orange or brown satin bow.", reactions: 58, isTopComment: false },
          { text: "Pine cones, acorns, some small orange pumpkins.", reactions: 43, isTopComment: false },
          { text: "Some filler glitter balls, some nuts (with shells) little green sprigs.", reactions: 31, isTopComment: false },
          { text: "Cranberries! Fresh ones add beautiful red pops of color.", reactions: 67, isTopComment: false },
          { text: "Dried corn cobs or Indian corn for traditional Thanksgiving look 🌽", reactions: 52, isTopComment: false },
          { text: "Velvet ribbon in burgundy or gold elevates the whole look.", reactions: 44, isTopComment: false },
          { text: "Pheasant feathers add an unexpected elegant touch!", reactions: 38, isTopComment: false },
          { text: "Copper or gold accents complement the natural browns beautifully.", reactions: 49, isTopComment: false },
          { text: "Burlap and lace combination is my favorite for rustic-chic!", reactions: 41, isTopComment: false },
          { text: "Pomegranates are gorgeous and seasonal! Split one open for drama.", reactions: 55, isTopComment: false },
          { text: "Dried hydrangeas in fall colors pair perfectly with pinecones.", reactions: 36, isTopComment: false },
          { text: "Mercury glass votives add sparkle without being too Christmas-y.", reactions: 47, isTopComment: false },
          { text: "Artichokes! Spray paint them gold for an unexpected centerpiece element.", reactions: 33, isTopComment: false },
          { text: "Chestnuts and walnuts in their shells add nice texture variety.", reactions: 42, isTopComment: false },
          { text: "Fresh herbs like rosemary and sage - pretty AND useful for cooking!", reactions: 61, isTopComment: false },
          { text: "Magnolia leaves are sturdy and last well in arrangements.", reactions: 29, isTopComment: false },
          { text: "Whatever you do, keep it low so guests can see each other across the table!", reactions: 54, isTopComment: false },
          { text: "I love how everyone's ideas are so different! Pinning all of these 📌", reactions: 38, isTopComment: false },
          { text: "Happy decorating everyone! Post pics of your tables! 🦃", reactions: 45, isTopComment: false },
        ],
      },
    ],
    relatedAnswers: [
      {
        id: "qa-1",
        question: "What are some DIY ideas for pinecone decorations?",
        answer: "Pinecone decorations can be a fun and creative DIY project, with various ideas shared by Facebook Group users, including making Christmas trees, ornaments, garlands, and centerpieces.",
        bullets: [
          "Just glue the pinecones onto wood slices, add tiny ornaments, and top them with a star.",
          "Collect pinecones, paint or glitter them if desired, and stack them into a tree shape using hot glue or a cone base.",
          "I took a snowflake from the Dollar tree and hot glued my pinecones on them. You could also cut the snowflakes out of cardboard.",
          "String together pinecones and small branches to create a natural garland for your mantle, stair railing, or tree.",
        ],
      },
      {
        id: "qa-2",
        question: "How to create a beautiful fall centerpiece using pinecones?",
        answer: "Creating a pinecone centerpiece can be as simple as filling a vase with pinecones and adding a candle, or getting creative with arrangements and decorations.",
        bullets: [
          "Fill your Clear Vase with pinecone's halfway, insert your Candle in the middle and continue adding remaining Cones to the top of vase.",
          "Gather Your Bounty: Look for vibrant fallen maple leaves, varying sizes of pinecones, textured acorns, dry seed pods, and small, knobby twigs or dried grass plumes.",
          "I glued 5 of them together into a star, secured them with a glued ribbon in the back to keep them connected.",
          "Don't forget to put them on a cookie tray and heat them for about 30 minutes on a low heat to kill any crawling critters and bacteria.",
        ],
      },
      {
        id: "qa-3",
        question: "What types of decorations go well with pinecones for a Thanksgiving theme?",
        answer: "Pinecones are a versatile decoration that can be paired with various elements to create a warm and inviting Thanksgiving theme.",
        bullets: [
          "White pumpkin or thick candle with fall foliage.",
          "Gourds, colorful leaves, orange or brown satin bow.",
          "Pine cones, acorns, some small orange pumpkins.",
          "Some filler glitter balls, some nuts (with shells) little green sprigs.",
        ],
      },
      {
        id: "qa-4",
        question: "Can you show me some rustic fall decor ideas with pinecones?",
        answer: "Rustic fall decor ideas with pinecones include creating a warm welcome with natural elements like pinecones, eucalyptus, and mini pumpkins.",
        bullets: [
          "Fill a rustic wooden crate with apples, mini gourds, or pinecones.",
          "Use grapevine as your base. Weave in dried wheat, eucalyptus sprigs, or even cinnamon sticks. Finish with a burlap or plaid ribbon.",
          "I cut & painted some pinecone flowers & glued them to a grapevine wreath to make a Fall decoration",
          "Look for five different textures outside: a handful of dried leaves, a few beautiful pinecones (scrubbed clean!), some seed pods.",
        ],
      },
      {
        id: "qa-5",
        question: "How to make a pinecone garland for my dining table?",
        answer: "To create a pinecone garland for your dining table, you can string together pinecones and small branches using twine or wire.",
        bullets: [
          "String together pinecones and small branches to create a natural garland for your mantle, stair railing, or tree.",
          "Attach pinecones to twine with hot glue or clothespins.",
          "Wrap either a foam or wire wreath frame with ribbon or burlap, then glue on pieces of pinecone.",
          "Use floral wire to wrap the bottom of pinecones, then wire them onto a wreath or garland.",
        ],
      },
    ],
    comments: [
      {
        author: { name: "Martha Stewart Fan", avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=64&h=64&fit=crop&crop=faces" },
        text: "Fill a clear vase halfway with pinecones, put a pillar candle in the middle, and add more pinecones around it. So simple but looks amazing!",
        reactions: 156,
      },
      {
        author: { name: "Crafty Carol", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=64&h=64&fit=crop&crop=faces" },
        text: "Pro tip: bake your pinecones at 200°F for 30 minutes before using them. Kills any bugs and makes them open up beautifully!",
        reactions: 98,
      },
      {
        author: { name: "DIY Diana", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=64&h=64&fit=crop&crop=faces" },
        text: "I spray painted some gold and silver, mixed with natural ones. The contrast is stunning especially with fairy lights!",
        reactions: 76,
      },
    ],
  },

  strangerthings: {
    id: "strangerthings",
    label: "Stranger Things",
    searchQuery: "stranger things season 5 release date",
    postTitle: "When is Stranger Things getting released?",
    aiOverview: {
      summary: `Stranger Things Season 5, the final season, is being released in three parts on Netflix: Volume 1 premiered November 26, 2025, Volume 2 releases December 25, 2025, and the series finale airs December 31, 2025.`,
      expandedText: `The final season promises an epic showdown with Vecna, who has survived and grown more powerful. Secrets long buried will rise, and the fate of not just Hawkins, but the entire world, rests in the hands of the kids who started it all.`,
    },
    groupData: {
      groupName: "Stranger Things Fans",
      groupAvatar: "https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?w=80&h=80&fit=crop",
      memberCount: "2.1M members",
      postBody: `Hey fellow fans! 📺

Does anyone know when the final season of Stranger Things is coming out? I've been waiting FOREVER and I'm dying to know what happens to Eleven and the gang. Also trying to plan a watch party so I need to know the exact dates!`,
      postAuthor: {
        name: "Alex Rivera",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=faces",
      },
    },
    searchResults: [
      {
        id: "result-1",
        postId: "post-st-1",
        commentsCount: 1247,
        timeAgo: "2 hours ago",
        title: "What's the plot of Stranger Things season 5?",
        description: "Does anyone know when the final season of Stranger Things is coming out? I've been waiting FOREVER and I'm dying to know what happens...",
        comments: [
          { text: "In the wake of Hawkins' devastation, Stranger Things 5 returns with the ultimate showdown between the forces of darkness and the last hope of humanity.", reactions: 892, isTopComment: true },
          { text: "Vecna has survived — more powerful and vengeful than ever — and the rift between the real world and the Upside Down has torn open, unleashing chaos unlike anything before.", reactions: 567, isTopComment: false },
          { text: "It's an emotional wrecking ball of a show. You go from heart-wrenching sadness to white-knuckle excitement.", reactions: 234, isTopComment: false },
          { text: "Secrets long buried will rise. Sacrifices must be made. And the fate of not just Hawkins, but the entire world, will rest in the hands of the kids who started it all.", reactions: 189, isTopComment: false },
          { text: "The Upside Down has merged with Hawkins and spread across the world. This is truly the endgame!", reactions: 445, isTopComment: false },
          { text: "Eleven has to make the ultimate sacrifice. I'm not ready for this emotionally 😭", reactions: 623, isTopComment: false },
          { text: "The Mind Flayer is back and more terrifying than ever. The creature designs this season are INSANE.", reactions: 389, isTopComment: false },
          { text: "Will finally gets his moment! His connection to the Upside Down is key to everything.", reactions: 512, isTopComment: false },
          { text: "The parallel with Eleven and Vecna's origins is chef's kiss storytelling 👨‍🍳", reactions: 298, isTopComment: false },
          { text: "I've watched Vol 1 three times already. Can't stop thinking about that ending!", reactions: 334, isTopComment: false },
          { text: "The callback to season 1 in episode 3 made me SOB. Full circle moment.", reactions: 421, isTopComment: false },
          { text: "Every episode feels like a movie. The production value is unreal!", reactions: 267, isTopComment: false },
          { text: "The Duffer Brothers really said 'we're going ALL OUT for the finale' 🔥", reactions: 378, isTopComment: false },
          { text: "Nancy's character arc this season is everything. Finally getting the development she deserves!", reactions: 234, isTopComment: false },
          { text: "That scene in episode 4 broke me. Won't spoil but if you know, you know. 💔", reactions: 567, isTopComment: false },
          { text: "The music choices this season are perfect. Kate Bush tribute in ep 2! 🎵", reactions: 289, isTopComment: false },
          { text: "I can't believe this is the end. Been watching since 2016. End of an era.", reactions: 445, isTopComment: false },
          { text: "Hot take: this might be the best season yet. And that's saying something!", reactions: 312, isTopComment: false },
          { text: "The way they're handling Max's storyline is so respectful and emotional.", reactions: 398, isTopComment: false },
          { text: "Christmas Day release for Vol 2 is CRUEL. I want to watch NOW! 😩", reactions: 256, isTopComment: false },
          { text: "Starting my rewatch of all seasons before the finale. Who's with me? 📺", reactions: 423, isTopComment: false },
          { text: "This show changed my life. Forever grateful to the Duffers for creating this world. ❤️", reactions: 534, isTopComment: false },
        ],
      },
      {
        id: "result-2",
        postId: "post-st-2",
        commentsCount: 856,
        timeAgo: "1 day ago",
        title: "When will Stranger Things season 5 be released?",
        description: "With the final season coming, what are your theories? How do you think they'll wrap everything up?",
        comments: [
          { text: "The final season of Stranger Things, Season 5, will be released in three parts on Netflix this fall. Volume 1 premieres November 26, 2025. Volume 2 releases December 25, 2025. The series finale debuts December 31, 2025.", reactions: 456, isTopComment: true },
          { text: "Stranger Things Season 5: Volume 1 is now officially streaming on Netflix worldwide, with Volume 2 being set to release on Christmas.", reactions: 234, isTopComment: false },
          { text: "Then Dec. 31st I'll marathon them all. I hate this splitting up the season crap.", reactions: 178, isTopComment: false },
          { text: "I will start binging previous seasons starting that the beginning of December and not the rest until the 31st.", reactions: 156, isTopComment: false },
          { text: "Perfect timing for New Year's Eve! Watch party plans incoming 🎉", reactions: 345, isTopComment: false },
          { text: "The wait between Vol 2 and the finale is only 6 days. Remember waiting 3 YEARS between seasons? 😂", reactions: 423, isTopComment: false },
          { text: "Setting up a projector for the finale. Going all out for this one!", reactions: 189, isTopComment: false },
          { text: "Christmas Day release means I'm watching with family whether they like it or not 🎄", reactions: 267, isTopComment: false },
          { text: "I took PTO for Dec 31st just for this. No regrets.", reactions: 312, isTopComment: false },
          { text: "The episodes are LONG this season. Finale is reportedly 2.5 hours! 🍿", reactions: 378, isTopComment: false },
          { text: "Netflix really said 'let's make this a cultural event' with this release schedule.", reactions: 234, isTopComment: false },
          { text: "My watch party snack list is already planned. Eggo waffles obviously! 🧇", reactions: 289, isTopComment: false },
          { text: "Anyone else avoiding social media until they've watched? Spoilers are EVERYWHERE.", reactions: 356, isTopComment: false },
          { text: "The global premiere event was incredible. So many tears from the cast!", reactions: 198, isTopComment: false },
          { text: "I've waited 8 years for this conclusion. Cannot believe it's finally here!", reactions: 445, isTopComment: false },
          { text: "Midnight release crew where you at? 🌙", reactions: 234, isTopComment: false },
          { text: "Pro tip: download episodes before release - servers will be SLAMMED.", reactions: 312, isTopComment: false },
          { text: "Making a drinking game for the finale. One sip for every time someone says 'Upside Down' 🥤", reactions: 178, isTopComment: false },
          { text: "The nostalgia is hitting different knowing this is the end 😢", reactions: 389, isTopComment: false },
          { text: "Happy watching everyone! What a journey it's been! 🙌", reactions: 267, isTopComment: false },
        ],
      },
      {
        id: "result-3",
        postId: "post-st-3",
        commentsCount: 423,
        timeAgo: "3 days ago",
        title: "Who are the main characters in the Stranger Things series?",
        description: "Trying to get my friends caught up before the finale. Who should they know about?",
        comments: [
          { text: "I love all of the main/reoccurring actors.. I don't think I have a favorite, especially now that Will's a badass", reactions: 312, isTopComment: true },
          { text: "My favorites are Will, Steve, Eddie, Jonathan, Robin, & Dustin.", reactions: 245, isTopComment: false },
          { text: "Dustin, Mike, Steve, El and Will", reactions: 189, isTopComment: false },
          { text: "Hopper is by far my favorite character.", reactions: 167, isTopComment: false },
          { text: "Steve's redemption arc from S1 bully to everyone's favorite babysitter is LEGENDARY 👑", reactions: 534, isTopComment: false },
          { text: "Eleven is the heart of the show. Millie Bobby Brown is incredible!", reactions: 423, isTopComment: false },
          { text: "Justice for Barb! Never forget season 1's best friend 💔", reactions: 198, isTopComment: false },
          { text: "Eddie Munson deserved better. Still not over it. 🦇🎸", reactions: 612, isTopComment: false },
          { text: "Max's storyline in S4 was the best character work the show has ever done.", reactions: 378, isTopComment: false },
          { text: "The whole Party dynamic is what makes this show. The friendships feel so real!", reactions: 289, isTopComment: false },
          { text: "Robin and Steve's friendship is everything. Best platonic duo in TV history.", reactions: 356, isTopComment: false },
          { text: "Joyce Byers - best TV mom ever. She never gave up on Will! 🏆", reactions: 267, isTopComment: false },
          { text: "Dustin's sense of humor carries so many scenes. Henderson for the win!", reactions: 234, isTopComment: false },
          { text: "Lucas really stepped up in S4. His scenes with Max were heartbreaking.", reactions: 198, isTopComment: false },
          { text: "Murray Bauman appreciation post! Comic relief king 👑", reactions: 178, isTopComment: false },
          { text: "The villains are top tier. Demogorgon → Mind Flayer → Vecna. Each one scarier!", reactions: 312, isTopComment: false },
          { text: "Nancy's character growth from S1 to now is incredible. Badass journalist energy!", reactions: 245, isTopComment: false },
          { text: "Jonathan and Will's brother bond hits different as a sibling myself 🥺", reactions: 189, isTopComment: false },
          { text: "Dr. Brenner is the character I love to hate. Such a complex villain.", reactions: 156, isTopComment: false },
          { text: "The casting for the kids was perfect. They've all grown up so much!", reactions: 423, isTopComment: false },
          { text: "Erica Sinclair steals every scene she's in. 'You can't spell America without Erica!' 🇺🇸", reactions: 378, isTopComment: false },
          { text: "This thread is making me want to rewatch EVERYTHING before the finale 📺", reactions: 234, isTopComment: false },
        ],
      },
    ],
    relatedAnswers: [
      {
        id: "qa-1",
        question: "What's the plot of Stranger Things season 5?",
        answer: "The plot of Stranger Things season 5 involves the ultimate showdown between the forces of darkness and the last hope of humanity.",
        bullets: [
          "In the wake of Hawkins' devastation, Stranger Things 5 returns with the ultimate showdown between the forces of darkness and the last hope of humanity.",
          "Vecna has survived — more powerful and vengeful than ever — and the rift between the real world and the Upside Down has torn open, unleashing chaos unlike anything before.",
          "It's an emotional wrecking ball of a show. You go from heart-wrenching sadness to white-knuckle excitement.",
          "Secrets long buried will rise. Sacrifices must be made. And the fate of not just Hawkins, but the entire world, will rest in the hands of the kids who started it all.",
        ],
      },
      {
        id: "qa-2",
        question: "When will Stranger Things season 5 be released?",
        answer: "Stranger Things season 5, the final season, is being released in three parts on Netflix.",
        bullets: [
          "The final season of Stranger Things, Season 5, will be released in three parts on Netflix this fall. Volume 1 premieres November 26, 2025. Volume 2 releases December 25, 2025. The series finale debuts December 31, 2025.",
          "Stranger Things Season 5: Volume 1 is now officially streaming on Netflix worldwide, with Volume 2 being set to release on Christmas.",
          "Then Dec. 31st I'll marathon them all. I hate this splitting up the season crap.",
          "I will start binging previous seasons starting that the beginning of December and not the rest until the 31st.",
        ],
      },
      {
        id: "qa-3",
        question: "What's the story behind the Upside Down?",
        answer: "The Upside Down in Stranger Things is believed to be a glitch created by Eleven's mind, distinct from Dimension X.",
        bullets: [
          "I believe that Eleven, being linked to the other world, unintentionally was able to alter the landscape of a specific part of Dimension X and have it glitch into a dark version of the town she was in.",
          "the upside down is stuck in time if eleven and vecna die and upside down is gone then they go back to that day when Will was taken",
          "Vecna sees this as a threat to his realm and seeks to end ours in order to sever the connection and stop the growth of any more upside downs.",
        ],
      },
      {
        id: "qa-4",
        question: "Who are the main characters in the Stranger Things series?",
        answer: "The main characters in the Stranger Things series include Eleven, Mike, Will, Dustin, Lucas, Joyce, Hopper, Steve, Max, and Robin.",
        bullets: [
          "I love all of the main/reoccurring actors.. I don't think I have a favorite, especially now that Will's a badass",
          "My favorites are Will, Steve, Eddie, Jonathan, Robin, & Dustin.",
          "Dustin, Mike, Steve, El and Will",
          "Hopper is by far my favorite character.",
        ],
      },
      {
        id: "qa-5",
        question: "What's the significance of Eleven's powers in the show?",
        answer: "Eleven's powers in the show are significant because they stem from her emotional state and are fueled by her experiences.",
        bullets: [
          "Eleven uses love to enhance her powers very often. the reason she was able to send henry away in the first place is because she pulled a memory of her mom telling her she loved her when she was born.",
          "She wasn't raised with that kind of love and compassion - although she does have it now... She is learning about love and friendship now.",
          "When Jane (011) uses her powers to attack she does so out of anger/hatred... Eleven clearly illustrates a pattern of embracing anger/fear/hatred to attack.",
          "The Strength of Will's powers come from his compassion and his positive feelings about the people he loves who support him.",
        ],
      },
    ],
    comments: [
      {
        author: { name: "Eleven_Stan", avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=64&h=64&fit=crop&crop=faces" },
        text: "It's split into 3 parts! Volume 1 dropped Nov 26, Volume 2 is Christmas Day, and the finale is New Year's Eve! Perfect way to end 2025!",
        reactions: 892,
      },
      {
        author: { name: "UpsideDownFan", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=64&h=64&fit=crop&crop=faces" },
        text: "Just finished Volume 1 and I'm SHOOK. Not gonna spoil anything but... prepare yourselves 😭",
        reactions: 567,
      },
      {
        author: { name: "HawkinsResident", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=64&h=64&fit=crop&crop=faces" },
        text: "Anyone else planning to rewatch all 4 seasons before the finale? Starting my marathon this weekend!",
        reactions: 234,
      },
    ],
    serp: {
      entityCard: {
        name: "Stranger Things",
        category: "TV show · Netflix",
        followers: "27M followers",
        profileImage: "https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?w=120&h=120&fit=crop",
        photos: [
          "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=200&h=200&fit=crop",
          "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=200&h=200&fit=crop",
          "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=200&h=200&fit=crop",
        ],
      },
      contentGrid: [
        { author: "Gregory Otto", timeAgo: "9h", reactions: "46.5K", imageUrl: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&h=600&fit=crop" },
        { author: "Ruby Patel", timeAgo: "1d", reactions: "46.5K", imageUrl: "https://images.unsplash.com/photo-1574267432553-4b4628081c31?w=400&h=600&fit=crop" },
        { author: "Romeo Jax", timeAgo: "5h", reactions: "6K", imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&h=600&fit=crop" },
        { author: "Justin Villanueva", timeAgo: "3d", reactions: "1.8K", imageUrl: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400&h=600&fit=crop" },
      ],
    },
  },
};

// Get topic by ID
export function getTopicData(topicId) {
  return topicsData[topicId] || topicsData.coffee;
}

// Get all topics for menu
export function getAllTopics() {
  return Object.values(topicsData).map(topic => ({
    id: topic.id,
    label: topic.label,
  }));
}

export default topicsData;


