import * as stylex from '@stylexjs/stylex';

/**
 * Color Tokens with automatic light/dark mode support
 */
export const colors = stylex.defineVars({
  accentColor: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#0866ff' },
  accentDeemphasized: { default: '#ebf5ff', '@media (prefers-color-scheme: dark)': 'rgba(29, 133, 252, 0.2)' },
  accentOnBackground: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#1d85fc' },
  activeDot: { default: '#080809', '@media (prefers-color-scheme: dark)': '#e2e5e9' },
  activeDotOnColor: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  activeDotOnMedia: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  activeIcon: { default: '#0064d1', '@media (prefers-color-scheme: dark)': '#ffffff' },
  alwaysBlack: { default: '#000000', '@media (prefers-color-scheme: dark)': '#000000' },
  alwaysBlackOverlay: { default: 'rgba(0, 0, 0, 0.4)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.4)' },
  alwaysTransparent: { default: 'rgba(0, 0, 0, 0)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0)' },
  alwaysWhite: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  attachmentFooterBackground: { default: '#f8f9fb', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.098)' },
  backgroundDeemphasized: { default: '#f2f4f7', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.098)' },
  blackSolidarityPrimaryButtonBackground: { default: '#080809', '@media (prefers-color-scheme: dark)': '#ffffff' },
  blackSolidarityPrimaryButtonText: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#080809' },
  blueLink: { default: '#0064d1', '@media (prefers-color-scheme: dark)': '#5aa7ff' },
  borderPersistentUi: { default: 'rgba(0, 0, 0, 0.047)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.098)' },
  borderResponsiveUi: { default: 'rgba(0, 0, 0, 0.098)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.047)' },
  borderUiEmphasis: { default: '#e2e5e9', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.047)' },
  borderUiEmphasisOnMedia: { default: 'rgba(0, 0, 0, 0.098)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.098)' },
  bottomSheetBackgroundDeemphasized: { default: '#f2f4f7', '@media (prefers-color-scheme: dark)': '#252728' },
  bottomSheetHandle: { default: '#84878b', '@media (prefers-color-scheme: dark)': '#6f7276' },
  cardBackground: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#333334' },
  cardBackgroundDark: { default: '#333334', '@media (prefers-color-scheme: dark)': '#333334' },
  cardBackgroundFlat: { default: '#f8f9fb', '@media (prefers-color-scheme: dark)': '#333334' },
  cardBackgroundLegacyWeb: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#252728' },
  cardBackgroundOnColor: { default: 'rgba(255, 255, 255, 0.149)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.149)' },
  cardBackgroundOnMedia: { default: 'rgba(28, 28, 29, 0.6)', '@media (prefers-color-scheme: dark)': 'rgba(28, 28, 29, 0.6)' },
  cardBorder: { default: 'rgba(0, 0, 0, 0)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0)' },
  cardShadowLight: { default: 'rgba(0, 0, 0, 0.047)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.098)' },
  cardShadowMedium: { default: 'rgba(0, 0, 0, 0.047)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.098)' },
  cardShadowStrong: { default: 'rgba(0, 0, 0, 0.098)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.149)' },
  clientBottomSheetPressed: { default: '#e8eaee', '@media (prefers-color-scheme: dark)': '#3b3c3e' },
  codeSyntaxComment: { default: '#65686c', '@media (prefers-color-scheme: dark)': '#b0b3b8' },
  codeSyntaxKeyword: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#5aa7ff' },
  codeSyntaxMethod: { default: '#b15b0f', '@media (prefers-color-scheme: dark)': '#f68628' },
  codeSyntaxNumber: { default: '#be438c', '@media (prefers-color-scheme: dark)': '#ff70c7' },
  codeSyntaxOperator: { default: '#887000', '@media (prefers-color-scheme: dark)': '#c3a000' },
  codeSyntaxString: { default: '#008168', '@media (prefers-color-scheme: dark)': '#14b898' },
  codeSyntaxText: { default: '#080809', '@media (prefers-color-scheme: dark)': '#e2e5e9' },
  commentBackground: { default: '#f0f2f5', '@media (prefers-color-scheme: dark)': '#333334' },
  commentBackgroundDeemphasized: { default: 'rgba(232, 234, 238, 0.6)', '@media (prefers-color-scheme: dark)': 'rgba(51, 51, 52, 0.6)' },
  commentBackgroundOnColor: { default: 'rgba(255, 255, 255, 0.149)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.149)' },
  commentBackgroundOnMedia: { default: 'rgba(28, 28, 29, 0.6)', '@media (prefers-color-scheme: dark)': 'rgba(28, 28, 29, 0.6)' },
  commentThreadingLines: { default: '#e2e5e9', '@media (prefers-color-scheme: dark)': '#46484b' },
  commentThreadingLinesOnColor: { default: 'rgba(255, 255, 255, 0.098)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.098)' },
  commentThreadingLinesOnMedia: { default: 'rgba(255, 255, 255, 0.149)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.149)' },
  contentLiquidityIg: { default: '#009ae5', '@media (prefers-color-scheme: dark)': '#009ae5' },
  datavizBluePrimary: { default: '#1d85fc', '@media (prefers-color-scheme: dark)': '#1d85fc' },
  datavizBlueSecondary: { default: '#043b72', '@media (prefers-color-scheme: dark)': '#ebf5ff' },
  datavizBlueTertiary: { default: '#ebf5ff', '@media (prefers-color-scheme: dark)': '#043b72' },
  datavizChartreusePrimary: { default: '#6a9316', '@media (prefers-color-scheme: dark)': '#6a9316' },
  datavizChartreuseSecondary: { default: '#324113', '@media (prefers-color-scheme: dark)': '#e2ff98' },
  datavizChartreuseTertiary: { default: '#e2ff98', '@media (prefers-color-scheme: dark)': '#324113' },
  datavizCyanPrimary: { default: '#008ed5', '@media (prefers-color-scheme: dark)': '#008ed5' },
  datavizCyanSecondary: { default: '#0f3f5d', '@media (prefers-color-scheme: dark)': '#e7f5ff' },
  datavizCyanTertiary: { default: '#e7f5ff', '@media (prefers-color-scheme: dark)': '#0f3f5d' },
  datavizFuchsiaPrimary: { default: '#fa2d8a', '@media (prefers-color-scheme: dark)': '#fa2d8a' },
  datavizFuchsiaSecondary: { default: '#760e3e', '@media (prefers-color-scheme: dark)': '#fff1f6' },
  datavizFuchsiaTertiary: { default: '#fff1f6', '@media (prefers-color-scheme: dark)': '#760e3e' },
  datavizGreenPrimary: { default: '#2b9a35', '@media (prefers-color-scheme: dark)': '#2b9a35' },
  datavizGreenSecondary: { default: '#1a441b', '@media (prefers-color-scheme: dark)': '#e3fae0' },
  datavizGreenTertiary: { default: '#e3fae0', '@media (prefers-color-scheme: dark)': '#1a441b' },
  datavizOrangePrimary: { default: '#d06c14', '@media (prefers-color-scheme: dark)': '#d06c14' },
  datavizOrangeSecondary: { default: '#5c310e', '@media (prefers-color-scheme: dark)': '#fff1e4' },
  datavizOrangeTertiary: { default: '#fff1e4', '@media (prefers-color-scheme: dark)': '#5c310e' },
  datavizPurplePrimary: { default: '#7d74ff', '@media (prefers-color-scheme: dark)': '#7d74ff' },
  datavizPurpleSecondary: { default: '#373279', '@media (prefers-color-scheme: dark)': '#f5f1ff' },
  datavizPurpleTertiary: { default: '#f5f1ff', '@media (prefers-color-scheme: dark)': '#373279' },
  datavizRedPrimary: { default: '#fb3c44', '@media (prefers-color-scheme: dark)': '#fb3c44' },
  datavizRedSecondary: { default: '#76161b', '@media (prefers-color-scheme: dark)': '#fff1ef' },
  datavizRedTertiary: { default: '#fff1ef', '@media (prefers-color-scheme: dark)': '#76161b' },
  datavizTealPrimary: { default: '#00987c', '@media (prefers-color-scheme: dark)': '#00987c' },
  datavizTealSecondary: { default: '#0a4438', '@media (prefers-color-scheme: dark)': '#e3f7f1' },
  datavizTealTertiary: { default: '#e3f7f1', '@media (prefers-color-scheme: dark)': '#0a4438' },
  datavizYellowPrimary: { default: '#a18400', '@media (prefers-color-scheme: dark)': '#a18400' },
  datavizYellowSecondary: { default: '#483b0c', '@media (prefers-color-scheme: dark)': '#fff6a1' },
  datavizYellowTertiary: { default: '#fff6a1', '@media (prefers-color-scheme: dark)': '#483b0c' },
  decorativeChatBlue: { default: '#00274d', '@media (prefers-color-scheme: dark)': '#00274d' },
  decorativeIconBlue: { default: '#0064d1', '@media (prefers-color-scheme: dark)': '#0064d1' },
  decorativeIconGreen: { default: '#3fbb46', '@media (prefers-color-scheme: dark)': '#3fbb46' },
  decorativeIconPink: { default: '#fa61ba', '@media (prefers-color-scheme: dark)': '#fa61ba' },
  decorativeIconPurple: { default: '#7d74ff', '@media (prefers-color-scheme: dark)': '#7d74ff' },
  decorativeIconRed: { default: '#fb3c44', '@media (prefers-color-scheme: dark)': '#fb3c44' },
  decorativeIconReels: { default: '#ff5757', '@media (prefers-color-scheme: dark)': '#ff5757' },
  decorativeIconTeal: { default: '#14b898', '@media (prefers-color-scheme: dark)': '#14b898' },
  decorativeIconWhatsapp: { default: '#25d366', '@media (prefers-color-scheme: dark)': '#25d366' },
  decorativeIconYellow: { default: '#f9cf00', '@media (prefers-color-scheme: dark)': '#f9cf00' },
  deemphasizedButtonIcon: { default: '#0064d1', '@media (prefers-color-scheme: dark)': '#75b6ff' },
  deviceBackground: { default: '#000000', '@media (prefers-color-scheme: dark)': '#000000' },
  deviceIcon: { default: '#000000', '@media (prefers-color-scheme: dark)': '#ffffff' },
  deviceIconOnColor: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  deviceIconOnMedia: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  deviceText: { default: '#000000', '@media (prefers-color-scheme: dark)': '#ffffff' },
  deviceTextOnColor: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  deviceTextOnMedia: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  disabledButtonBackground: { default: '#e2e5e9', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.098)' },
  disabledButtonBackgroundGrowth: { default: '#5aa7ff', '@media (prefers-color-scheme: dark)': '#5aa7ff' },
  disabledIcon: { default: '#b0b3b8', '@media (prefers-color-scheme: dark)': '#6f7276' },
  disabledIconOnColor: { default: 'rgba(255, 255, 255, 0.898)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.898)' },
  disabledIconOnMedia: { default: 'rgba(255, 255, 255, 0.498)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.498)' },
  disabledText: { default: '#b0b3b8', '@media (prefers-color-scheme: dark)': '#6f7276' },
  disabledTextOnColor: { default: 'rgba(255, 255, 255, 0.898)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.898)' },
  disabledTextOnMedia: { default: 'rgba(255, 255, 255, 0.498)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.498)' },
  dismissBackground: { default: 'rgba(255, 255, 255, 0.302)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.302)' },
  divider: { default: '#d0d3d7', '@media (prefers-color-scheme: dark)': '#65686c' },
  dividerOnColor: { default: '#5c5e62', '@media (prefers-color-scheme: dark)': '#5c5e62' },
  dividerOnMedia: { default: '#5c5e62', '@media (prefers-color-scheme: dark)': '#5c5e62' },
  dotBadgeBlue: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#1d85fc' },
  eventDate: { default: '#dd2334', '@media (prefers-color-scheme: dark)': '#dd2334' },
  fbLitehighlight: { default: '#ebf5ff', '@media (prefers-color-scheme: dark)': '#ebf5ff' },
  fbLitewash: { default: '#b0b3b8', '@media (prefers-color-scheme: dark)': '#080809' },
  fbLogo: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#0866ff' },
  fbWordmark: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  fbliteRtcAnswerBackground: { default: '#3fbb46', '@media (prefers-color-scheme: dark)': '#3fbb46' },
  fbliteRtcDismissBackground: { default: 'rgba(255, 255, 255, 0.298)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.298)' },
  footerBackground: { default: '#f8f9fb', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.102)' },
  glimmerBaseOpaque: { default: '#979a9f', '@media (prefers-color-scheme: dark)': '#ffffff' },
  glimmerHighContrastBaseOpaque: { default: '#65686c', '@media (prefers-color-scheme: dark)': '#ffffff' },
  glimmerHighContrastButtonPressed: { default: 'rgba(208, 211, 215, 0.149)', '@media (prefers-color-scheme: dark)': 'rgba(208, 211, 215, 0.149)' },
  glimmerIndex0: { default: 'rgba(101, 104, 108, 0.169)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.2)' },
  glimmerIndex1: { default: 'rgba(101, 104, 108, 0.137)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.157)' },
  glimmerIndex2: { default: 'rgba(101, 104, 108, 0.098)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.118)' },
  glimmerIndex3: { default: 'rgba(101, 104, 108, 0.067)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.086)' },
  glimmerIndex4: { default: 'rgba(101, 104, 108, 0.039)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.047)' },
  hiddenCommentOverlay: { default: 'rgba(255, 255, 255, 0.6)', '@media (prefers-color-scheme: dark)': 'rgba(37, 39, 40, 0.6)' },
  highContrastButtonPressed: { default: 'rgba(208, 211, 215, 0.149)', '@media (prefers-color-scheme: dark)': 'rgba(208, 211, 215, 0.149)' },
  hostedViewSelectedState: { default: '#ebf5ff', '@media (prefers-color-scheme: dark)': 'rgba(29, 133, 252, 0.098)' },
  hovered: { default: 'rgba(70, 72, 75, 0.149)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.149)' },
  icon: { default: '#b0b3b8', '@media (prefers-color-scheme: dark)': '#6f7276' },
  iconOnMedia: { default: 'rgba(255, 255, 255, 0.8)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.8)' },
  inactiveDot: { default: '#b0b3b8', '@media (prefers-color-scheme: dark)': '#84878b' },
  inactiveDotOnColor: { default: 'rgba(255, 255, 255, 0.498)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.498)' },
  inactiveDotOnMedia: { default: 'rgba(255, 255, 255, 0.498)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.498)' },
  inputBarBackground: { default: '#f0f2f5', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.102)' },
  inputInactiveInnerBorder: { default: '#d0d3d7', '@media (prefers-color-scheme: dark)': '#5c5e62' },
  instantFeedbackBorder: { default: 'rgba(0, 0, 0, 0)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0)' },
  instantFeedbackShadow: { default: 'rgba(0, 0, 0, 0.047)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.098)' },
  lastActiveStateBackground: { default: '#f2fcf0', '@media (prefers-color-scheme: dark)': '#152b14' },
  lastActiveStateText: { default: '#1e5e21', '@media (prefers-color-scheme: dark)': '#90e78a' },
  legacyTooltipBackground: { default: 'rgba(255, 255, 255, 0.8)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.8)' },
  like: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#3e93f8' },
  linkOnColor: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  linkOnMedia: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  live: { default: '#dd2334', '@media (prefers-color-scheme: dark)': '#dd2334' },
  logo: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  love: { default: '#dd2334', '@media (prefers-color-scheme: dark)': '#ff5757' },
  mapHighlightBackground: { default: 'rgba(8, 102, 255, 0.2)', '@media (prefers-color-scheme: dark)': 'rgba(29, 133, 252, 0.447)' },
  mapHighlightBorder: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#0866ff' },
  mediaHovered: { default: 'rgba(0, 0, 0, 0.051)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.051)' },
  mediaInnerBorder: { default: 'rgba(0, 0, 0, 0.098)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.047)' },
  mediaPressed: { default: 'rgba(70, 72, 75, 0.149)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.2)' },
  metaIcon: { default: '#65686c', '@media (prefers-color-scheme: dark)': '#b0b3b8' },
  metaIconOnColor: { default: 'rgba(255, 255, 255, 0.898)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.898)' },
  metaIconOnMedia: { default: 'rgba(255, 255, 255, 0.8)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.8)' },
  metaText: { default: '#65686c', '@media (prefers-color-scheme: dark)': '#b0b3b8' },
  metaTextOnColor: { default: 'rgba(255, 255, 255, 0.898)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.898)' },
  metaTextOnMedia: { default: 'rgba(255, 255, 255, 0.8)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.8)' },
  navBarBackground: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#252728' },
  negative: { default: '#dd2334', '@media (prefers-color-scheme: dark)': '#ff7c74' },
  negativeDeemphasized: { default: '#ffe3de', '@media (prefers-color-scheme: dark)': 'rgba(185, 24, 40, 0.2)' },
  newNotificationBackground: { default: '#e7f3ff', '@media (prefers-color-scheme: dark)': 'rgba(45, 136, 255, 0.098)' },
  nonMediaHovered: { default: 'rgba(0, 0, 0, 0.047)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.047)' },
  nonMediaPressed: { default: 'rgba(70, 72, 75, 0.149)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.2)' },
  nonMediaPressedOnDark: { default: 'rgba(255, 255, 255, 0.298)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.298)' },
  notificationBackground: { default: '#e7f3ff', '@media (prefers-color-scheme: dark)': 'rgba(45, 136, 255, 0.102)' },
  notificationBadge: { default: '#dd2334', '@media (prefers-color-scheme: dark)': '#dd2334' },
  notificationCircleBlue: { default: '#1d85fc', '@media (prefers-color-scheme: dark)': '#1d85fc' },
  notificationCircleFbPay: { default: '#003464', '@media (prefers-color-scheme: dark)': '#003464' },
  notificationCircleGray: { default: '#84878b', '@media (prefers-color-scheme: dark)': '#84878b' },
  notificationCircleGreen: { default: '#2b9a35', '@media (prefers-color-scheme: dark)': '#2b9a35' },
  notificationCircleOrange: { default: '#f68628', '@media (prefers-color-scheme: dark)': '#f68628' },
  notificationCirclePink: { default: '#de51a4', '@media (prefers-color-scheme: dark)': '#de51a4' },
  notificationCirclePurple: { default: '#7d74ff', '@media (prefers-color-scheme: dark)': '#7d74ff' },
  notificationCircleRed: { default: '#fb3c44', '@media (prefers-color-scheme: dark)': '#fb3c44' },
  notificationCircleTeal: { default: '#00ae8f', '@media (prefers-color-scheme: dark)': '#00ae8f' },
  notificationCircleYellow: { default: '#f9cf00', '@media (prefers-color-scheme: dark)': '#f9cf00' },
  optimisticPostTint: { default: 'rgba(255, 255, 255, 0.6)', '@media (prefers-color-scheme: dark)': 'rgba(37, 39, 40, 0.6)' },
  overlayOnMedia: { default: 'rgba(0, 0, 0, 0.8)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.8)' },
  overlayOnMediaExtraLight: { default: 'rgba(0, 0, 0, 0.2)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.2)' },
  overlayOnMediaLight: { default: 'rgba(0, 0, 0, 0.349)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.349)' },
  overlayOnSurface: { default: 'rgba(0, 0, 0, 0.4)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.6)' },
  persistentCtaShadow: { default: 'rgba(0, 0, 0, 0.098)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.149)' },
  persistentUi: { default: 'rgba(0, 0, 0, 0.051)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.102)' },
  placeholderIcon: { default: '#65686c', '@media (prefers-color-scheme: dark)': '#b0b3b8' },
  placeholderIconOnColor: { default: 'rgba(255, 255, 255, 0.898)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.898)' },
  placeholderIconOnMedia: { default: 'rgba(255, 255, 255, 0.498)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.498)' },
  placeholderImage: { default: '#979a9f', '@media (prefers-color-scheme: dark)': '#979a9f' },
  placeholderTextDefault: { default: '#65686c', '@media (prefers-color-scheme: dark)': '#b0b3b8' },
  placeholderTextOnColor: { default: 'rgba(255, 255, 255, 0.898)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.898)' },
  placeholderTextOnMedia: { default: 'rgba(255, 255, 255, 0.8)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.8)' },
  popoverBackground: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#3b3c3e' },
  positive: { default: '#24832c', '@media (prefers-color-scheme: dark)': '#3fbb46' },
  positiveDeemphasized: { default: '#f2fcf0', '@media (prefers-color-scheme: dark)': '#121f10' },
  postTint: { default: 'rgba(255, 255, 255, 0.6)', '@media (prefers-color-scheme: dark)': 'rgba(37, 39, 40, 0.6)' },
  pressed: { default: 'rgba(70, 72, 75, 0.349)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.302)' },
  primaryButtonBackground: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#0866ff' },
  primaryButtonBackgroundOnColor: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  primaryButtonBackgroundOnMedia: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  primaryButtonIcon: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  primaryButtonIconOnColor: { default: '#000000', '@media (prefers-color-scheme: dark)': '#000000' },
  primaryButtonIconOnMedia: { default: '#080809', '@media (prefers-color-scheme: dark)': '#080809' },
  primaryButtonText: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  primaryButtonTextOnColor: { default: '#000000', '@media (prefers-color-scheme: dark)': '#000000' },
  primaryButtonTextOnMedia: { default: '#080809', '@media (prefers-color-scheme: dark)': '#080809' },
  primaryDeemphasizedButtonBackground: { default: '#ebf5ff', '@media (prefers-color-scheme: dark)': 'rgba(29, 133, 252, 0.2)' },
  primaryDeemphasizedButtonIcon: { default: '#0064d1', '@media (prefers-color-scheme: dark)': '#75b6ff' },
  primaryDeemphasizedButtonText: { default: '#0064d1', '@media (prefers-color-scheme: dark)': '#75b6ff' },
  primaryIcon: { default: '#080809', '@media (prefers-color-scheme: dark)': '#f2f4f7' },
  primaryIconOnColor: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  primaryIconOnMedia: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  primaryText: { default: '#080809', '@media (prefers-color-scheme: dark)': '#f2f4f7' },
  primaryTextOnColor: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  primaryTextOnMedia: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  progressRingBlueBackground: { default: 'rgba(8, 102, 255, 0.2)', '@media (prefers-color-scheme: dark)': 'rgba(8, 102, 255, 0.2)' },
  progressRingBlueForeground: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#0866ff' },
  progressRingDisabledBackground: { default: 'rgba(176, 179, 184, 0.2)', '@media (prefers-color-scheme: dark)': 'rgba(111, 114, 118, 0.2)' },
  progressRingDisabledForeground: { default: '#b0b3b8', '@media (prefers-color-scheme: dark)': '#6f7276' },
  progressRingNeutralBackground: { default: 'rgba(0, 0, 0, 0.2)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.2)' },
  progressRingNeutralForeground: { default: '#000000', '@media (prefers-color-scheme: dark)': '#ffffff' },
  progressRingOnColorBackground: { default: 'rgba(255, 255, 255, 0.149)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.149)' },
  progressRingOnColorForeground: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  progressRingOnMediaBackground: { default: 'rgba(255, 255, 255, 0.2)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.2)' },
  progressRingOnMediaForeground: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  progressRingWarningBackground: { default: 'rgba(212, 175, 0, 0.2)', '@media (prefers-color-scheme: dark)': 'rgba(212, 175, 0, 0.2)' },
  progressRingWarningForeground: { default: '#d4af00', '@media (prefers-color-scheme: dark)': '#d4af00' },
  ratingStarActive: { default: '#e0761a', '@media (prefers-color-scheme: dark)': '#ff9a42' },
  ratingStarActiveOnColor: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  ratingStarActiveOnMedia: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  reactionAnger: { default: '#dd2334', '@media (prefers-color-scheme: dark)': '#ff5757' },
  reactionHaha: { default: '#887000', '@media (prefers-color-scheme: dark)': '#f9cf00' },
  reactionLike: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#3e93f8' },
  reactionLove: { default: '#dd2334', '@media (prefers-color-scheme: dark)': '#ff5757' },
  reactionSorry: { default: '#887000', '@media (prefers-color-scheme: dark)': '#f9cf00' },
  reactionSupport: { default: '#887000', '@media (prefers-color-scheme: dark)': '#f9cf00' },
  reactionWow: { default: '#887000', '@media (prefers-color-scheme: dark)': '#f9cf00' },
  responsiveUi: { default: 'rgba(0, 0, 0, 0.102)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.102)' },
  secondaryButtonBackground: { default: '#e2e5e9', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.1)' },
  secondaryButtonBackgroundFloating: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#46484b' },
  secondaryButtonBackgroundOnColor: { default: 'rgba(255, 255, 255, 0.149)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.149)' },
  secondaryButtonBackgroundOnColorDeprecated: { default: 'rgba(0, 0, 0, 0.047)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.098)' },
  secondaryButtonBackgroundOnMedia: { default: 'rgba(28, 28, 29, 0.6)', '@media (prefers-color-scheme: dark)': 'rgba(28, 28, 29, 0.6)' },
  secondaryButtonIcon: { default: '#080809', '@media (prefers-color-scheme: dark)': '#f2f4f7' },
  secondaryButtonIconOnColor: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  secondaryButtonIconOnMedia: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  secondaryButtonPressed: { default: 'rgba(0, 0, 0, 0.047)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.2)' },
  secondaryButtonText: { default: '#080809', '@media (prefers-color-scheme: dark)': '#f2f4f7' },
  secondaryButtonTextOnColor: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  secondaryButtonTextOnMedia: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  secondaryIcon: { default: '#65686c', '@media (prefers-color-scheme: dark)': '#b0b3b8' },
  secondaryIconOnColor: { default: 'rgba(255, 255, 255, 0.898)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.898)' },
  secondaryIconOnMedia: { default: 'rgba(255, 255, 255, 0.8)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.8)' },
  secondaryText: { default: '#65686c', '@media (prefers-color-scheme: dark)': '#b0b3b8' },
  secondaryTextOnColor: { default: 'rgba(255, 255, 255, 0.898)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.898)' },
  secondaryTextOnMedia: { default: 'rgba(255, 255, 255, 0.8)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.8)' },
  seeLessSelectedSubtopic: { default: '#a18400', '@media (prefers-color-scheme: dark)': '#a18400' },
  seeMoreSelectedSubtopic: { default: '#2b9a35', '@media (prefers-color-scheme: dark)': '#2b9a35' },
  seen: { default: '#84878b', '@media (prefers-color-scheme: dark)': '#84878b' },
  shadowPersistentUi: { default: 'rgba(0, 0, 0, 0.098)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.298)' },
  shadowResponsiveUi: { default: 'rgba(0, 0, 0, 0.098)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.098)' },
  shadowTextAndIconOnMedia: { default: 'rgba(0, 0, 0, 0.62)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.62)' },
  shadowTextAndIconOnOverlayExtraLight: { default: 'rgba(0, 0, 0, 0.161)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.161)' },
  shadowUiEmphasis: { default: 'rgba(0, 0, 0, 0.098)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.098)' },
  sheetBackgroundDeemphasized: { default: '#f2f4f7', '@media (prefers-color-scheme: dark)': '#252728' },
  stepperActive: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#0866ff' },
  stepperInactive: { default: '#d0d3d7', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.2)' },
  storySeen: { default: '#84878b', '@media (prefers-color-scheme: dark)': '#84878b' },
  storyUnseen: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#0866ff' },
  strongSecondary: { default: '#3b3c3e', '@media (prefers-color-scheme: dark)': '#d0d3d7' },
  surfaceBackground: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#252728' },
  switchCheckedBackgroundColorAndroid: { default: '#3e93f8', '@media (prefers-color-scheme: dark)': '#add5ff' },
  switchCheckedBackgroundColorIos: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#0866ff' },
  switchCheckedHandleFillColorAndroid: { default: '#00488c', '@media (prefers-color-scheme: dark)': '#0866ff' },
  switchCheckedHandleFillColorIos: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  switchDisabledBackgroundColor: { default: '#f2f4f7', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.098)' },
  switchDisabledHandleFillColor: { default: '#b0b3b8', '@media (prefers-color-scheme: dark)': '#6f7276' },
  switchUncheckedBackgroundColor: { default: '#8f9297', '@media (prefers-color-scheme: dark)': '#6f7276' },
  switchUncheckedHandleFillColor: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  temporarydisabledButtonBackgroundGrowth: { default: '#5aa7ff', '@media (prefers-color-scheme: dark)': '#5aa7ff' },
  text: { default: '#65686c', '@media (prefers-color-scheme: dark)': '#b0b3b8' },
  textHighlight: { default: 'rgba(8, 102, 255, 0.2)', '@media (prefers-color-scheme: dark)': 'rgba(29, 133, 252, 0.447)' },
  textInputActiveInnerBorder: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#1d85fc' },
  textInputActiveOuterBorder: { default: '#ebf5ff', '@media (prefers-color-scheme: dark)': 'rgba(29, 133, 252, 0.2)' },
  textInputActiveText: { default: '#0064d1', '@media (prefers-color-scheme: dark)': '#3e93f8' },
  textInputBarBackground: { default: '#f0f2f5', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.098)' },
  textInputBarBackgroundOnColor: { default: 'rgba(255, 255, 255, 0.098)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.098)' },
  textInputBarBackgroundOnDeemphasized: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#333334' },
  textInputBarBackgroundOnMedia: { default: 'rgba(28, 28, 29, 0.6)', '@media (prefers-color-scheme: dark)': 'rgba(28, 28, 29, 0.6)' },
  textInputInactiveInnerBorder: { default: '#8f9297', '@media (prefers-color-scheme: dark)': '#6f7276' },
  textInputInactiveOuterBorder: { default: 'rgba(0, 0, 0, 0)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0)' },
  threadingLines: { default: '#e2e5e9', '@media (prefers-color-scheme: dark)': '#46484b' },
  threadingLinesOnColor: { default: 'rgba(255, 255, 255, 0.102)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.102)' },
  toggleActiveBackground: { default: '#ebf5ff', '@media (prefers-color-scheme: dark)': '#1d85fc' },
  toggleActiveIcon: { default: '#0064d1', '@media (prefers-color-scheme: dark)': '#ffffff' },
  toggleActiveText: { default: '#0064d1', '@media (prefers-color-scheme: dark)': '#ffffff' },
  tooltipBackground: { default: 'rgba(0, 0, 0, 0.8)', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.8)' },
  tooltipShadow: { default: 'rgba(0, 0, 0, 0.047)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.098)' },
  tooltipText: { default: '#e2e5e9', '@media (prefers-color-scheme: dark)': '#080809' },
  ufiTrayIconButtonBackground: { default: '#e2e5e9', '@media (prefers-color-scheme: dark)': '#46484b' },
  uiEmphasis: { default: '#e2e5e9', '@media (prefers-color-scheme: dark)': 'rgba(255, 255, 255, 0.051)' },
  uncheckedBackgroundColor: { default: '#8f9297', '@media (prefers-color-scheme: dark)': '#6f7276' },
  verifiedBadge: { default: '#0866ff', '@media (prefers-color-scheme: dark)': '#e8eaee' },
  verifiedBadgeOnColor: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  verifiedBadgeOnMedia: { default: '#ffffff', '@media (prefers-color-scheme: dark)': '#ffffff' },
  viewSelectedState: { default: '#ebf5ff', '@media (prefers-color-scheme: dark)': 'rgba(29, 133, 252, 0.102)' },
  warning: { default: '#af8f00', '@media (prefers-color-scheme: dark)': '#af8f00' },
  wash: { default: '#c9ccd1', '@media (prefers-color-scheme: dark)': '#1c1c1d' },
  webLegacyTooltipBackground: { default: 'rgba(255, 255, 255, 0.8)', '@media (prefers-color-scheme: dark)': 'rgba(0, 0, 0, 0.8)' },
  webWash: { default: '#f2f4f7', '@media (prefers-color-scheme: dark)': '#1c1c1d' },
  wow: { default: '#887000', '@media (prefers-color-scheme: dark)': '#f9cf00' }
});

// Export individual color groups for convenience
export const accentColors = {
  primary: colors.accentColor,
  deemphasized: colors.accentDeemphasized,
  onBackground: colors.accentOnBackground,
};

export const textColors = {
  primary: colors.primaryText,
  secondary: colors.secondaryText,
  device: colors.deviceText,
  meta: colors.metaText,
  disabled: colors.disabledText,
  placeholder: colors.placeholderTextDefault,
};

export const iconColors = {
  primary: colors.primaryIcon,
  secondary: colors.secondaryIcon,
  active: colors.activeIcon,
  disabled: colors.disabledIcon,
  device: colors.deviceIcon,
  meta: colors.metaIcon,
  placeholder: colors.placeholderIcon,
};

export const backgroundColors = {
  surface: colors.surfaceBackground,
  card: colors.cardBackground,
  deemphasized: colors.backgroundDeemphasized,
  wash: colors.wash,
  webWash: colors.webWash,
  comment: colors.commentBackground,
  device: colors.deviceBackground,
  notification: colors.notificationBackground,
};

export const buttonColors = {
  primaryBackground: colors.primaryButtonBackground,
  primaryText: colors.primaryButtonText,
  primaryIcon: colors.primaryButtonIcon,
  secondaryBackground: colors.secondaryButtonBackground,
  secondaryText: colors.secondaryButtonText,
  secondaryIcon: colors.secondaryButtonIcon,
  disabled: colors.disabledButtonBackground,
};

export const borderColors = {
  default: colors.divider,
  card: colors.cardBorder,
  uiEmphasis: colors.borderUiEmphasis,
  persistentUi: colors.borderPersistentUi,
  responsiveUi: colors.borderResponsiveUi,
};

export const semanticColors = {
  positive: colors.positive,
  negative: colors.negative,
  warning: colors.warning,
  like: colors.like,
  love: colors.love,
  live: colors.live,
};
